VERSION 0.7

build:
    FROM quay.io/defn/dev:latest-nix-installed
    ENTRYPOINT ["/home/ubuntu/.nix-profile/bin/nix", "develop", "--command", "bash", "-c"]
    CMD ["bash -il"]
    RUN echo source $HOME/.nix-profile/share/nix-direnv/direnvrc > /home/ubuntu/.direnvrc
    RUN echo export DIRENV_LOG_FORMAT= >> /home/ubuntu/.bashrc
    COPY . .
    RUN git init && git add . && git commit -m "initial commit"
    RUN direnv allow
    SAVE IMAGE meh
