mod bazel 'common/bazel.Justfile'
mod coder 'common/coder.Justfile'
mod tilt 'common/tilt.Justfile'
mod github 'common/github.Justfile'
mod gpg 'common/gpg.Justfile'
mod aws 'common/aws.Justfile'
mod playbook 'common/playbook.Justfile'
mod lib 'common/lib.Justfile'

# Run a playbook
play pb *lim:
	just playbook::playbook {{pb}} {{lim}}

# Run a command
command pattern *args:
	just playbook::command {{pattern}} {{args}}

# Use this workspace
[no-cd]
use *name:
	just coder::use {{name}}