mod bazel 'common/bazel.Justfile'
mod coder 'common/coder.Justfile'
mod tilt 'common/tilt.Justfile'
mod github 'common/github.Justfile'
mod gpg 'common/gpg.Justfile'
mod aws 'common/aws.Justfile'
mod playbook 'common/playbook.Justfile'

# Run a playbook
play pb *lim:
	just playbook::playbook {{pb}} {{lim}}

# Use this workspace
[no-cd]
use:
	just coder::use