#!/usr/bin/env python

load("ext://restart_process", "custom_build_with_restart")

# local registry
default_registry("coder-amanibhavam-district.tail3884f.ts.net:5000")

# code-server
local_resource(
    "code-server",
    serve_cmd=[
        "bash",
        "-c",
        """
            cd
            source .bash_profile
            cd ~/m/pkg/codeserver
            exec nix develop --command code-server --auth none --port 13337
        """,
    ],
)

# tailscale serve
local_resource(
    "tailscale-server",
    serve_cmd=[
        "bash",
        "-c",
        """
            cd
            source .bash_profile
            tailscale serve --tcp 443 --bg --yes 8443
            tailscale serve --https 5000 --bg --yes https+insecure://localhost:4999/
            tailscale serve --https 10350 --bg --yes 10350 
            while [[ -z "$(kubectl --context $(uname -n) get -n traefik svc traefik -o json | jq -r .spec.clusterIP || true)" ]]; do sleep 1; done
            set -x
            exec socat TCP-LISTEN:8443,fork TCP:$(kubectl --context $(uname -n) get -n traefik svc traefik -o json | jq -r .spec.clusterIP):443
        """,
    ],
)

# kubernetes tunnel
#local_resource(
#    "kubernetes-tunnel",
#    serve_cmd=[
#        "bash",
#        "-c",
#        """
#            cd
#            source .bash_profile
#	        tailscale serve --bg --https 6556 https+insecure://127.0.0.1:6555
#            exec socat TCP-LISTEN:6555,bind=127.0.0.1,fork TCP:$(ifconfig -a ens5 | grep ' inet ' | awk '{print $2}'):6443
#        """,
#    ],
#)

# swap
local_resource(
    "swap",
    serve_cmd=[
        "bash",
        "-c",
        """
            if [[ "$(df -klh /mnt | tail -1 | awk '{print $NF}')" == "/mnt" ]]; then
                if ! test -f /mnt/swap; then
                    sudo dd if=/dev/zero of=/mnt/swap bs=1M count=8192
                fi
                sudo chmod 0600 /mnt/swap
                sudo mkswap /mnt/swap || true
                sudo swapon /mnt/swap || true
            fi
            sleep infinity
        """,
    ],
)
