#!/usr/bin/env python

# fuck off
analytics_settings(False)

load("ext://restart_process", "custom_build_with_restart")

# local registry
default_registry("169.254.32.1:5000")

# code-server
local_resource(
    "code-server",
    serve_cmd=[
        "bash",
        "-c",
        """
            cd ~/m
            exec code-server --auth none --port 13337
            """,
    ],
)

# coder
local_resource(
    "coder",
    serve_cmd=[
        "bash",
        "-c",
        """
            cd ~/m
            make dev
            """,
    ],
)

# tailscaled
local_resource(
    "tailscaled",
    serve_cmd=[
        "bash",
        "-c",
        """
            cd
            sudo $(which tailscaled)
            """,
    ],
)

# hacks
local_resource(
    "hacks",
    serve_cmd=[
        "bash",
        "-c",
        """
            while true; do
                cd ~/m/c/dfd
                make label
                sleep 30
            done
            """,
    ],
)
