#!/usr/bin/env bash

#MISE description="Deploy Astro artifacts to Cloudflare workers"

set -efu -o pipefail

cd "${MISE_ORIGINAL_CWD}"
npm wrangler deploy -c wrangler-rpc.toml
npm wrangler deploy -c wrangler-do.toml
npm wrangler deploy -c wrangler.toml
