#!/usr/bin/env bash

exec 2>&1

export STARSHIP_NO=1
source ~/.bash_profile
mise trust
mise install
source .env
export PATH

if [[ -n ${CODER_INIT_SCRIPT_BASE64-} ]]; then
	echo ${CODER_INIT_SCRIPT_BASE64} | base64 -d |
		sed 's#agent$#agent '"${CODER_NAME}"'#; s#^while.*#while ! test -x ${BINARY_NAME}; do#; s#^BINARY_NAME.*#BINARY_NAME='"$HOME"'/bin/nix/coder#; s#exec ./#exec #; s#exit 1#echo exit 1#; s#output=$(./#output=$(#' \
			>/tmp/coder-init-script-${CODER_NAME}-$$
	exec bash -x /tmp/coder-init-script-${CODER_NAME}-$$
fi

exec mise exec -- coder agent
