#!/usr/bin/env python

# fuck off
analytics_settings(False)

load("ext://restart_process", "custom_build_with_restart")

# local registry
default_registry("169.254.32.1:5000")

# hacks
local_resource(
    "tutorial",
    serve_cmd=[
        "bash",
        "-c",
        """
        sleep infinity
        """,
    ],
)
