package api

info: {
	title:   *"Generated by cue." | string
	version: *"v1.2.3" | string
}

#Script: {
	script!:  string
	workdir!: string
	user?:    string
	group?:   string
	umask?:   string
	result?:  string
	...
}
