#!/usr/bin/env bash

set -efu

dir="$1"
shift
output="$1"
shift

max=10000
if [[ -n ${1-} ]]; then
	max="$1"
	shift
fi

cat all.input | shuf | head -${max} > ${output}.input
cat ${output}.input | bash etc/cols.sh no "${dir}" >${output}.html.1
mv ${output}.html.1 ${output}.html

echo "$(date) $(cat ${output}.input | wc -l)"
