#!/usr/bin/env bash

set -efu

dir="$1"
shift
output="$1"
shift

max=10000
if [[ -n ${1-} ]]; then
	max="$1"
	shift
fi

(
	find yes no -type f
	find no -type f
) | cut -d/ -f2 | cut -d. -f1 | sort | uniq -c | grep ' 1 ' | awk '{print $2}' >${output}.input.1
mv ${output}.input.1 ${output}.input

cat ${output}.input | head -${max} | bash etc/cols.sh no "${dir}" >${output}.html.1
mv ${output}.html.1 ${output}.html

echo "$(date) $(cat ${output}.input | wc -l)"
