#!/usr/bin/env bash

set -efu

dir="$1"
shift
num="$1"
shift
output="$1"
shift

(
	find yes no -type f
	find no -type f
) | cut -d/ -f2 | cut -d. -f1 | sort | uniq -c | grep ' 1 ' | awk '{print $2}' >${output}.input.1
mv ${output}.input.1 ${output}.input

cat ${output}.input | shuf | head -10000 | bash etc/cols.sh no "${dir}" "${num}" /replicate/t2 >${output}.html.1
mv ${output}.html.1 ${output}.html

echo "$(date) $(cat ${output}.input | wc -l)"
