SHELL := /bin/bash

# Dump all data from the pb (database) module
# Dependencies: ../pb directory with Makefile, make command
# Outputs: Executed dump target in pb directory with limit=all parameter
dump:
	cd ../pb && $(MAKE) dump limit=all
