#!/usr/bin/env expect

set timeout 600

spawn easyrsa build-client-full client nopass

expect {
  "pass phrase" {
    send "this-is-password\r"
    exp_continue
  }
  "Confirm request details:" {
    send "yes\r"
    exp_continue
  }
}

#expect eof
