VERSION 0.8

build:
    ARG image=cache.defn.run:5000/dfd:base
    BUILD --platform=linux/amd64 +root --image=${image}

root:
    ARG image

    FROM ubuntu:22.04

    USER root

    ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ENV container=docker

    ENV LANG en_US.UTF-8
    ENV LANGUAGE en_US:en
    ENV LC_ALL en_US.UTF-8
    ENV DEBIAN_FRONTEND=noninteractive

    COPY --dir script script
    RUN script/000-install-bare
    RUN script/001-install-base
    RUN script/999-update

    ENTRYPOINT []
    CMD []

    USER ubuntu
    ENV USER=ubuntu
    ENV HOME=/home/ubuntu
    WORKDIR /home/ubuntu

    SAVE IMAGE --push ${image}
