brew "bash-completion@2"
brew "direnv"
brew "pass"
brew "pinentry-mac"
brew "pstree"
brew "ykman"
brew "git"

cask "divvy"
cask "iterm2"
cask "docker"
cask "little-snitch"
cask "google-chrome"
cask "visual-studio-code"
