#!/usr/bin/env python

load("ext://restart_process", "custom_build_with_restart")

# local kubernetes
allow_k8s_contexts("dfd")

# local registry
default_registry("169.254.32.1:5000")

# bazel
local_resource(
    "bazel",
    serve_cmd=["b", "watch"],
)

cli_build = "../bazel-bin/dev/dev_/dev"
cli_release = "/tmp/cli"
cli_entrypoint = "/cli"

# api initial deploy
k8s_yaml(local("cat deploy.yaml"))

# api builds when cmd/, command/ changes
local_resource(name="cli", 
    cmd="if test -f {build}; then sudo cp {build} {release} && sudo chmod 755 {release}; fi".format(build=cli_build, release=cli_release), 
    deps=[cli_build])

# api service selected from deploy
k8s_resource("api")

# api updates when api builds
custom_build_with_restart(
    ref="api",
    command="cd .. && make image tag=$EXPECTED_REF",
    deps=[cli_release],
    trigger=[cli_release],
    entrypoint=[cli_entrypoint],
    live_update=[
        sync(cli_release, cli_entrypoint),
    ],
)
