#!/usr/bin/env python

# fuck off
analytics_settings(False)

load("ext://restart_process", "custom_build_with_restart")

# local registry
default_registry("169.254.32.1:5000")

# bazel
local_resource(
    "bazel",
    serve_cmd=["b", "watch"],
)
