// Generated by Wrangler by running `wrangler types`

interface Env {
  kv: KVNamespace;
  GREETING: "world";
  mydo: DurableObjectNamespace /* MyDurableObject from my-do */;
  bucket: R2Bucket;
  db: D1Database;
  ASSETS: Fetcher;
}
