status:
    mise exec -- fly machine list

build:
    docker pull ghcr.io/defn/dev
    mise exec -- fly deploy --local-only --build-only

deploy:
    docker pull ghcr.io/defn/dev
    mise exec -- fly deploy --local-only
    
stop:
    mise exec -- fly machine stop $(fly machine list --json | jq -r '.[].id')

start:
    mise exec -- fly machine start $(fly machine list --json | jq -r '.[].id')

restart:
    mise exec -- fly machine restart $(fly machine list --json | jq -r '.[].id')

logs:
    fly logs -a "$(basename $(pwd))"
