status:
    fly machine list

build:
    docker pull ghcr.io/defn/dev
    fly deploy --local-only --build-only

deploy:
    docker pull ghcr.io/defn/dev
    fly deploy --local-only
    
stop:
    fly machine stop $(fly machine list --json | jq -r '.[].id')

start:
    fly machine start $(fly machine list --json | jq -r '.[].id')

restart:
    fly machine restart $(fly machine list --json | jq -r '.[].id')
