VERSION 0.6

tower:
    FROM registry.fly.io/defn:dev-tower

defn0:
    FROM +tower
    RUN --push --secret FLY_ACCESS_TOKEN ~/bin/e flyctl scale --app defn count 0

defn1:
    FROM +tower
    RUN --push --secret FLY_ACCESS_TOKEN ~/bin/e flyctl scale --app defn count 1
