#!/usr/bin/env bash

function main {
    chown ubuntu:ubuntu /mnt

    mkdir -p /mnt/work /mnt/.password-store /mnt/.gnupg
    chown -R ubuntu:ubuntu /mnt/work /mnt/.password-store /mnt/.gnupg /mnt/home
    ln -nfs /mnt/work ~ubuntu/
    ln -nfs /mnt/.password-store ~ubuntu/
    ln -nfs /mnt/.gnupg ~ubuntu/
    ln -nfs /mnt/home/gitconfig .gitconfig

    mkdir -p /mnt/tailscale
    chown -R root:root /mnt/tailscale
    rm -rf /var/lib/tailscale
    ln -nfs /mnt/tailscale /var/lib/tailscale

    mkdir -p ~ubuntu/.ssh
    echo "${SSH_KEY}" | tee ~ubuntu/.ssh/authorized_keys

    chown -R ubuntu:ubuntu ~ubuntu

    #(cd /var/lib/docker && exec dockerd) &
    (cd /var/lib/tailscale && exec tailscaled) &

    if [[ -n "${BUILDKITE_AGENT_TOKEN:-}" ]]; then
        sed -i "s/xxx/${BUILDKITE_AGENT_TOKEN}/g" /etc/buildkite-agent/buildkite-agent.cfg
        sed -i "s/^name=.*/name=\"${FLY_APP_NAME}-%spawn\"/g" /etc/buildkite-agent/buildkite-agent.cfg
        (exec buildkite-agent start --tags "queue=${FLY_APP_NAME}") &
    fi

    if [[ "$#" -gt 0 ]]; then
        (if cd ~ubuntu; then exec "$@"; fi) &
    fi

    exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o StreamLocalBindUnlink=yes
}

main "$@"
