up:
    tilt up

server:
    python -m venv venv
    venv/bin/pip install -r requirements.txt
    venv/bin/python main.py

build:
    b build
    b run tutorial_html__copy
    chmod 0640 tutorial.html
    trunk fmt tutorial.html

# TODO: write an implementation of just check
check:
    git grep -r TOD[O] . || true
