#!/usr/bin/env python

load("{{cookiecutter.common}}/Tiltfile", "main")

main(
    app_entrypoint="/cli",
    app_release="gen/cli.bin",
    app_build="../../bazel-bin/{{cookiecutter.path}}/{{cookiecutter.package}}_/{{cookiecutter.package}}",
    host="{{cookiecutter.project_name}}",
)
