#!/usr/bin/env python

v1alpha1.extension_repo(name="custom", load_host="defn", url="file:///home/ubuntu/m")

load("ext://defn/common", "main")

main(
    app_entrypoint="/cli",
    app_release="gen/cli.bin",
    app_build="../../bazel-bin/{{cookiecutter.path}}/{{cookiecutter.package}}_/{{cookiecutter.package}}",
    host="{{cookiecutter.project_name}}",
)
