#!/usr/bin/env bash

#MISE description="Run a playbook locally"
#USAGE arg "playbook" help="Path to playbook"

cd "${MISE_ORIGINAL_CWD}"

if ! test -r "${usage_playbook}"; then
	if test -r "${HOME}/m/pb/${usage_playbook}.yaml"; then
		usage_playbook="${HOME}/m/pb/${usage_playbook}.yaml"
	fi
fi

ansible-playbook "${usage_playbook}" -i localhost, -c local </dev/null 2>&1
