#!/usr/bin/env bash

#MISE description="Run a playbook"
#USAGE arg "playbook" help="Path to playbook"
#USAGE arg "limit" help="Limit to hosts" default=""

cd "${MISE_ORIGINAL_CWD}"

if [[ -z ${usage_limit} ]]; then
	usage_limit="$(ansible-inventory --list | jq -r '._meta.hostvars | keys | sort | .[]' | fzf --select-1)"
fi

if ! test -r "${usage_playbook}"; then
	if test -r "${HOME}/m/pb/${usage_playbook}.yaml"; then
		usage_playbook="${HOME}/m/pb/${usage_playbook}.yaml"
	fi
fi

ansible-playbook "${usage_playbook}" -l "${usage_limit}"
