VERSION 0.7

build:
    ARG image=169.254.32.1:5000/dfd
    BUILD +build-pod --image=${image}

build-pod:
    ARG image
    BUILD +image-pod --image=${image}

image-pod:
    ARG image

    FROM +pod
    SAVE IMAGE --push ${image}

pod:
    FROM quay.io/defn/dev:latest

    RUN git clone https://github.com/defn/dev dev \
        && mv dev/.git . \
        && rm -rf dev \
        && git reset --hard

    RUN bash -c 'source .bashrc && ~/bin/persist-cache && make nix home'
    RUN bash -c 'source .bashrc && for e in vscodevim.vim tamasfe.even-better-toml jnoortheen.nix-ide hashicorp.terraform golang.go esbenp.prettier-vscode bazelbuild.vscode-bazel cuelang.cue marp-team.marp-vscode; do bin/nix/code-server serve-local --force --install-extension $e; done'
    RUN bash -c 'source .bashrc && cd ~/m && ~/bin/persist-cache && go install golang.org/x/tools/gopls@latest && go install honnef.co/go/tools/cmd/staticcheck@latest && cd && git checkout .'

    USER root
    RUN install -d -m 0755 -o ubuntu -g ubuntu /cache
    RUN install -d -m 0755 -o ubuntu -g ubuntu /cache/git

    USER ubuntu
    RUN --no-cache bash -c 'mkdir /cache/git/https---github-com-defn-dev-git && cd /cache/git/https---github-com-defn-dev-git && git clone --mirror -v -- https://github.com/defn/dev.git .'

    RUN --no-cache git pull