# Run tilt to start servers and builds
up:
    tilt up

# Build the software
build:
    b build
    b run tutorial_html__copy
    chmod 0640 tutorial.html
    trunk fmt tutorial.html

# Run a python web service
server:
    python -m venv venv
    venv/bin/pip install -r requirements.txt
    venv/bin/python main.py

# Run a check script
check:
    true

# Make a lesson cutout from 0002 template 
cutout name:
    cookiecutter -f 0002 --no-input project_name={{ name }} path={{ name }} \
        server_port="$( (git grep port=5 */main.py | perl -pe 's{.*?port=}{}; s{\)}{}'; seq 5000 5999) | sort | uniq -c | grep -v ' 2 ' | awk '{print $2}' | head -1)" \
        tilt_port="$( (git grep TILT_PORT */.env | perl -pe 's{.*TILT_PORT=}{}' | grep ^2; seq 20000 20999 ) | sort | uniq -c | grep -v ' 2 ' | awk '{print $2}' | head -1)"
