#!/usr/bin/env bash

function main {
  set -exfu

  cat << EOF | sudo tee /etc/apt/apt.conf.d/local
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};

DPkg::Lock::Timeout "-1";
EOF

  apt purge --auto-remove -y unattended-upgrades
}

main "$@"
