#!/usr/bin/env bash

function main {
  if ! [[ "$(whoami)" == "app" ]]; then
    exec sudo -H -i -u app "$0" "$@"
    return $?
  fi

  set -exfu

  local aptget="env DEBIAN_FRONTEND=noninteractive apt-get"

  curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo apt-key add -
  curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | sudo tee /etc/apt/sources.list.d/tailscale.list

  sudo $aptget update
  sudo $aptget install tailscale
}

main "$@"
