#!/usr/bin/env bash

function main {
  if ! [[ "$(whoami)" == "ubuntu" ]]; then
    exec sudo -H -i -u ubuntu "$0" "$@"
    return $?
  fi

  set -exfu

  ssh -o StrictHostKeyChecking=no git@github.com true || true
  git clone https://github.com/defn/dev home
  mv home/.git .
  rm -rf home
  git reset --hard
  git submodule update --init
  set +x
  source .bashrc
  ln -nfs /mnt/work .
  for a in $(cat .tool-versions | grep -v python | awk '{print $1}' ); do asdf plugin-add $a; asdf install $a; done
  set -x
}

main "$@"
