#!/usr/bin/env bash

function main {
	# Start OCI registry (idempotent)
	docker rm -f k3d-registry 2>/dev/null || true
	docker run -d --name k3d-registry --restart always -p 169.254.32.1:5000:5000 -v k3d-registry:/var/lib/registry registry:2

	k3d cluster delete --config k3d.yaml
	k3d cluster create --config k3d.yaml
	kubectl config set-context --current --namespace=argocd

	tput smcup             # enter alternate screen
	trap 'tput rmcup' EXIT # restore on exit

	while kubectl get deployments,statefulsets -A --no-headers | talign 3 | perl -ne '$found++ if !/(\d+)\/\1/ && print; END { exit 1 unless $found }'; do
		sleep 5
		clear
	done
}

main "$@"
