#!/usr/bin/env bash

function main {
	mise upgrade --bump argocd

	curl -sSL -o argocd.yaml https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
	cue import argocd.yaml -f -R -p k3d -l '"kube"' -l '"argocd"' -l 'kind' -l metadata.name
	rm -f argocd.yaml
	cue cmd dump | yq eval 'select(.metadata.namespace == null) .metadata.namespace = "argocd"' >argocd.yaml

	trunk fmt
	cue fmt
}

main "$@"
