VERSION 0.7

build:
    ARG K3S
    ARG image
    BUILD +build-k3d --image=${image} --K3S=${K3S}

build-k3d:
    ARG K3S
    ARG image
    BUILD +image-k3d --image=${image} --K3S=${K3S}

image-k3d:
    ARG K3S
    ARG image

    FROM +k3d --K3S=${K3S}
    SAVE IMAGE --push ${image}

home:
    FROM quay.io/defn/dev:latest

    USER root

    RUN apt update && apt install -y git

    USER ubuntu
    WORKDIR /home/ubuntu

    RUN curl -L https://releases.nixos.org/nix/nix-2.17.0/install > nix-install \
        && bash nix-install --no-daemon \
        && rm -f nix-install

    RUN git clone https://github.com/defn/dev dev \
        && mv dev/.git . \
        && rm -rf dev \
        && git reset --hard

    RUN . ~/.nix-profile/etc/profile.d/nix.sh \
        && mkdir -p /nix/bin \
        && cd m/pkg \
        && for a in tailscale util-linux k3d nix shell; do \
            (cd $a && nix develop --command bash -c \
                'for b in $(IFS=:; for a in $PATH; do echo $a; done | grep /nix/store | tac); do find $b -type f; done | xargs | while read -r bins; do ln -nfs $bins /nix/bin/; done'); \
            done

    SAVE ARTIFACT /nix nix
    SAVE ARTIFACT /home home

k3d:
    ARG K3S

    FROM rancher/k3s:v${K3S}

    RUN echo root:x:0: >> /etc/group \
        && echo ubuntu:x:1000: >> /etc/group \
        && echo root:x:0:0:root:/root:/bin/sh >> /etc/passwd \
        && echo ubuntu:x:1000:1000:root:/home/ubuntu:/bin/sh >> /etc/passwd \
        && install -d -m 0700 -o root -g root /root \
        && mkdir -p /home && install -d -m 0700 -o ubuntu -g ubuntu /home/ubuntu

    COPY --dir --chown=ubuntu:ubuntu +home/nix /nix
    COPY --dir --chown=ubuntu:ubuntu +home/home /

    RUN ln -nfs /bin/env /usr/bin/env

    RUN mkdir -p /var/lib/rancher/k3s/agent/etc/containerd
    COPY k3d-config.toml var/lib/rancher/k3s/agent/etc/containerd/config.toml
    RUN mv /bin/k3s /bin/k3s-real && for a in kubectl k3s-server k3s-secrets-encrypt k3s-etcd-snapshot k3s-completion k3s-certificate k3s-agent k3s-token crictl ctr containerd; do ln -nfs k3s-real /bin/$a; done
    COPY k3s-wrapper.sh /bin/k3s

    RUN cp /nix/bin/bash /bin/bash
    RUN sed 's#/bin/sh#/bin/bash#' -i /etc/passwd
    RUN /bin/bash -c "ln -nfsv /nix/store/*util-linux*/bin/* /bin/"
    RUN /bin/bash -c "ln -nfsv /nix/store/*tailscale*/bin/* /bin/"
    RUN cp /nix/bin/bash /bin/bash

    USER ubuntu
    RUN --no-cache cd && /nix/bin/git pull

    USER root
