build:
    PATH=$PATH:$HOME/.cargo/bin cargo install worker-build
    PATH=$PATH:$HOME/.cargo/bin worker-build --release 
    workerd compile config.capnp > hello
    chmod 755 hello

serve:
    ./hello
