#!/usr/bin/env bash

exec 2>&1
bin="$(basename "$(pwd)")"
if test -x "${bin}"; then
	bin="./${bin}"
else
	bin="../../bazel-bin/svc.d/${bin}/${bin}_/${bin}"
fi
if test -r .env; then
	source .env
fi
exec ~/bin/with-env "${bin}"
