#!/usr/bin/env python

# slidev
local_resource(
    "slidev",
    serve_cmd=[
        "bash",
        "-c",
        """
            npm install
            npm run dev -- --remote --open=false
            """,
    ],
)
