#!/usr/bin/env bash

function main {
    set -efu

    local cmd="$1"; shift
    local args=""

    for a in "$@"; do args="${args}${args:+ }$(echo -n "${a}" | base64)"; done

    exec cue cmd -t args="${args}" "${cmd}"
}

main "$@"
