#!/usr/bin/env bash

function main {
	set -exfu

	sudo chgrp ubuntu /var/run/docker.sock
	sudo chmod 0770 /var/run/docker.sock
	sudo chown ubuntu:ubuntu /workspaces
	(
		set +f
		sudo ln -nfs /Users/*/work ~/work
	)

	cd && (git pull || true)
}

main "$@"
