#!/usr/bin/env bash

function main {
	set -exfu

	if [[ -d /mnt/home/.ssh ]]; then
		install -d -m 0700 -o ubuntu -g ubuntu /home/ubuntu/.ssh
		install -m 0600 -o ubuntu -g ubuntu /mnt/home/.ssh/authorized_keys /home/ubuntu/.ssh/
	fi

	if [[ -d /mnt/home/.gnupg ]]; then
		install -d -m 0700 -o ubuntu -g ubuntu /home/ubuntu/.gnupg
		install -m 0600 -o ubuntu -g ubuntu /mnt/home/.gnupg/trustdb.gpg /home/ubuntu/.gnupg/
		install -m 0600 -o ubuntu -g ubuntu /mnt/home/.gnupg/pubring.kbx /home/ubuntu/.gnupg/
	fi

	ln -nfs /mnt/home/.password-store /home/ubuntu/

	exec /usr/bin/tini -- /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
}

main "$@"
