#!/usr/bin/env bash

function main {
	set -exfu

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		cd
		git pull
		set +exfu
		source .bash_profile
		set -exfu

		make install

		exit $?
	fi
}

main "$@"
