import '../Justfile'

list:
	@mkdir -p ~/.config/gh
	@yq --yaml-output -n --arg token "$(b github)" --arg handle "${GIT_COMMITTER_NAME}" '{"github.com": { users: { "\($handle)": { oauth_token: $token}}, git_protocol: "https", user: $handle, oauth_token: $token}}' > ~/.config/gh/hosts.yml
	@./make_list_vendor_updates.sh

latest:
	env NIX_CONFIG="access-tokens = github.com=$(b github)" j update upgrade	

update:
	@./make_update_flakes.sh

upgrade:
	n upgrade && n all update pkg deps
	n upgrade && n all update pkg deps || true
	git commit --allow-empty -m "finished upgrade"
