ARG FROM=ghcr.io/defn/dev:latest

FROM ${FROM}

RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN bin/with-env make sync || true
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN bin/with-env make sync

ENTRYPOINT ["/home/ubuntu/m/entrypoint.sh"]
CMD []
