VERSION 0.8

root:
    ARG image=coder-amanibhavam-district.tail3884f.ts.net:5000/dfd:class
    ARG vsextensions="vscodevim.vim jnoortheen.nix-ide hashicorp.terraform golang.go esbenp.prettier-vscode bazelbuild.vscode-bazel cuelang.cue pbkit.vscode-pbkit marp-team.marp-vscode tailscale.vscode-tailscale geequlim.godot-tools alfish.godot-files ms-python.python"

    FROM ubuntu:22.04

    USER root

    ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ENV container=docker

    ENV LANG en_US.UTF-8
    ENV LANGUAGE en_US:en
    ENV LC_ALL en_US.UTF-8
    ENV DEBIAN_FRONTEND=noninteractive

    COPY --dir script script
    RUN script/001-install-base
    RUN rm -rf script

    USER ubuntu
    ENV USER=ubuntu
    ENV HOME=/home/ubuntu
    WORKDIR /home/ubuntu
    COPY --dir script script
    RUN script/800-defn-dev
    RUN script/999-defn-dev
    RUN rm -rf script

    CACHE /home/ubuntu/work

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    RUN sudo chown ubuntu:ubuntu /home/ubuntu/work && chmod 755 /home/ubuntu/work

    RUN git config --global user.email "you@example.com" && git config --global user.name "Your Name" && git pull

    COPY --dir script script
    RUN script/999-defn-dev
    RUN rm -rf script

    RUN bash -c 'source .bash_profile && for e in ${vsextensions}; do bin/nix/code-server serve-local --force --install-extension $e; done'
    RUN bash -c 'source .bash_profile && mkdir -p work && bin/persist-cache && cd m && go install golang.org/x/tools/gopls@latest && go install honnef.co/go/tools/cmd/staticcheck@latest'

    ENTRYPOINT []
    CMD []

    SAVE IMAGE --push ${image}-buildkite-latest

class:
    ARG image=coder-amanibhavam-district.tail3884f.ts.net:5000/dfd:class-buildkite-latest
    FROM ${image}

    RUN --no-cache bash -c 'git config --global user.email "you@example.com" && git config --global user.name "Your Name" && git pull'
    RUN bash -c 'source .bash_profile && make home && cd m && b build'
    RUN git checkout .

    COPY --dir script script
    RUN script/999-defn-dev
    RUN rm -rf script

    SAVE IMAGE --push ${image}

buildkite:
    ARG image=coder-amanibhavam-district.tail3884f.ts.net:5000/dfd:buildkite
    FROM ghcr.io/buildkite/agent-stack-k8s/agent:0.7.0

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    RUN git clone --mirror -v -- https://github.com/defn/dev.git ${BUILDKITE_GIT_MIRRORS_PATH}/https---github-com-defn-dev-git
    RUN --no-cache cd ${BUILDKITE_GIT_MIRRORS_PATH}/https---github-com-defn-dev-git && git fetch origin
    SAVE IMAGE --push ${image}
