# Build and push Docker images for multiple platforms
# Description: Builds multi-platform Docker images and pushes to GitHub Container Registry
# Dependencies: docker, git, buildkit, qemu, buildkite env vars, just
# Outputs: Multi-platform Docker images pushed to ghcr.io/defn/dev
latest platforms="amd64":
	#!/usr/bin/env bash
	set -efu -o pipefail

	case "${BUILDKITE_BRANCH:-}" in
		main)
			case "${BUILDKITE_MESSAGE:-}" in
				"chore(main): release"*)
					# wait for the release tag to be created when a release commit is merged to main branch
					# the wait allows please-release to run in github actions
					# it is not guaranteed that the tag will be created in time
					sleep 30
					;;
			esac
			;;
	esac

	git fetch || true

	docker run --rm --privileged tonistiigi/binfmt --install all
	docker run --rm --privileged multiarch/qemu-user-static:latest --reset -p yes --credential yes

	export BUILD_SHA="$(git rev-parse HEAD)"
	export RELEASE="$(git describe --tags --abbrev=0)"
	export GITHUB_TOKEN="$(cd .. && just github::token)"

	for p in {{ platforms }}; do
		(
			docker build -t ghcr.io/defn/dev:${RELEASE}-$p \
					--platform linux/$p \
					--build-arg RELEASE \
					--secret id=GITHUB_TOKEN .

			docker push ghcr.io/defn/dev:${RELEASE}-$p

			docker build --no-cache -t ghcr.io/defn/dev:latest-${RELEASE}-${BUILD_SHA}-${p} -f Dockerfile.latest \
					--platform linux/$p \
					--build-arg FROM=ghcr.io/defn/dev:${RELEASE}-${p} \
					--secret id=GITHUB_TOKEN .

			docker push ghcr.io/defn/dev:latest-${RELEASE}-${BUILD_SHA}-${p}
		) &
	done

	wait

	docker manifest rm ghcr.io/defn/dev:latest 2>/dev/null >/dev/null || true
	docker manifest create ghcr.io/defn/dev:latest ghcr.io/defn/dev:latest-${RELEASE}-${BUILD_SHA}-amd64
	docker manifest push ghcr.io/defn/dev:latest
