#!/usr/bin/env python

local_resource(
    "prefect",
    serve_cmd=["just", "prefect"],
)

local_resource(
    "minio",
    serve_cmd=["just", "minio"],
)

local_resource(
    "run ",
    cmd=["just", "run"],
)
