VERSION --use-registry-for-with-docker --ci-arg 0.7

build:
    ARG image
    BUILD +image --image=${image}

nix-archive:
    FROM ubuntu
    COPY *.tar.gz .
    RUN for a in *.tar.gz; do echo $a; tar xfz $a -C /; done
    SAVE ARTIFACT /nix nix

image:
    FROM ubuntu
    ARG image
    COPY aws_config.txt .
    COPY app_config .
    COPY --dir +nix-archive/nix /nix
    SAVE IMAGE ${image}