//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cmd) DeepCopyInto(out *Cmd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cmd.
func (in *Cmd) DeepCopy() *Cmd {
	if in == nil {
		return nil
	}
	out := new(Cmd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cmd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdList) DeepCopyInto(out *CmdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cmd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdList.
func (in *CmdList) DeepCopy() *CmdList {
	if in == nil {
		return nil
	}
	out := new(CmdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CmdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdSpec) DeepCopyInto(out *CmdSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.RestartOn != nil {
		in, out := &in.RestartOn, &out.RestartOn
		*out = new(RestartOnSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StartOn != nil {
		in, out := &in.StartOn, &out.StartOn
		*out = new(StartOnSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableSource != nil {
		in, out := &in.DisableSource, &out.DisableSource
		*out = new(DisableSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdSpec.
func (in *CmdSpec) DeepCopy() *CmdSpec {
	if in == nil {
		return nil
	}
	out := new(CmdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdStateRunning) DeepCopyInto(out *CmdStateRunning) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdStateRunning.
func (in *CmdStateRunning) DeepCopy() *CmdStateRunning {
	if in == nil {
		return nil
	}
	out := new(CmdStateRunning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdStateTerminated) DeepCopyInto(out *CmdStateTerminated) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdStateTerminated.
func (in *CmdStateTerminated) DeepCopy() *CmdStateTerminated {
	if in == nil {
		return nil
	}
	out := new(CmdStateTerminated)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdStateWaiting) DeepCopyInto(out *CmdStateWaiting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdStateWaiting.
func (in *CmdStateWaiting) DeepCopy() *CmdStateWaiting {
	if in == nil {
		return nil
	}
	out := new(CmdStateWaiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdStatus) DeepCopyInto(out *CmdStatus) {
	*out = *in
	if in.Waiting != nil {
		in, out := &in.Waiting, &out.Waiting
		*out = new(CmdStateWaiting)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(CmdStateRunning)
		(*in).DeepCopyInto(*out)
	}
	if in.Terminated != nil {
		in, out := &in.Terminated, &out.Terminated
		*out = new(CmdStateTerminated)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableStatus != nil {
		in, out := &in.DisableStatus, &out.DisableStatus
		*out = new(DisableStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdStatus.
func (in *CmdStatus) DeepCopy() *CmdStatus {
	if in == nil {
		return nil
	}
	out := new(CmdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMap) DeepCopyInto(out *ConfigMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMap.
func (in *ConfigMap) DeepCopy() *ConfigMap {
	if in == nil {
		return nil
	}
	out := new(ConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapDisableSource) DeepCopyInto(out *ConfigMapDisableSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapDisableSource.
func (in *ConfigMapDisableSource) DeepCopy() *ConfigMapDisableSource {
	if in == nil {
		return nil
	}
	out := new(ConfigMapDisableSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapList) DeepCopyInto(out *ConfigMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapList.
func (in *ConfigMapList) DeepCopy() *ConfigMapList {
	if in == nil {
		return nil
	}
	out := new(ConfigMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapStateSource) DeepCopyInto(out *ConfigMapStateSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapStateSource.
func (in *ConfigMapStateSource) DeepCopy() *ConfigMapStateSource {
	if in == nil {
		return nil
	}
	out := new(ConfigMapStateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisableResourceStatus) DeepCopyInto(out *DisableResourceStatus) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]DisableSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisableResourceStatus.
func (in *DisableResourceStatus) DeepCopy() *DisableResourceStatus {
	if in == nil {
		return nil
	}
	out := new(DisableResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisableSource) DeepCopyInto(out *DisableSource) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ConfigMapDisableSource)
		**out = **in
	}
	if in.EveryConfigMap != nil {
		in, out := &in.EveryConfigMap, &out.EveryConfigMap
		*out = make([]ConfigMapDisableSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisableSource.
func (in *DisableSource) DeepCopy() *DisableSource {
	if in == nil {
		return nil
	}
	out := new(DisableSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisableStatus) DeepCopyInto(out *DisableStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisableStatus.
func (in *DisableStatus) DeepCopy() *DisableStatus {
	if in == nil {
		return nil
	}
	out := new(DisableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecAction) DeepCopyInto(out *ExecAction) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecAction.
func (in *ExecAction) DeepCopy() *ExecAction {
	if in == nil {
		return nil
	}
	out := new(ExecAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extension) DeepCopyInto(out *Extension) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extension.
func (in *Extension) DeepCopy() *Extension {
	if in == nil {
		return nil
	}
	out := new(Extension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Extension) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionList) DeepCopyInto(out *ExtensionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Extension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionList.
func (in *ExtensionList) DeepCopy() *ExtensionList {
	if in == nil {
		return nil
	}
	out := new(ExtensionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExtensionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionRepo) DeepCopyInto(out *ExtensionRepo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionRepo.
func (in *ExtensionRepo) DeepCopy() *ExtensionRepo {
	if in == nil {
		return nil
	}
	out := new(ExtensionRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExtensionRepo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionRepoList) DeepCopyInto(out *ExtensionRepoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExtensionRepo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionRepoList.
func (in *ExtensionRepoList) DeepCopy() *ExtensionRepoList {
	if in == nil {
		return nil
	}
	out := new(ExtensionRepoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExtensionRepoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionRepoSpec) DeepCopyInto(out *ExtensionRepoSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionRepoSpec.
func (in *ExtensionRepoSpec) DeepCopy() *ExtensionRepoSpec {
	if in == nil {
		return nil
	}
	out := new(ExtensionRepoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionRepoStatus) DeepCopyInto(out *ExtensionRepoStatus) {
	*out = *in
	in.LastFetchedAt.DeepCopyInto(&out.LastFetchedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionRepoStatus.
func (in *ExtensionRepoStatus) DeepCopy() *ExtensionRepoStatus {
	if in == nil {
		return nil
	}
	out := new(ExtensionRepoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionSpec) DeepCopyInto(out *ExtensionSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionSpec.
func (in *ExtensionSpec) DeepCopy() *ExtensionSpec {
	if in == nil {
		return nil
	}
	out := new(ExtensionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionStatus) DeepCopyInto(out *ExtensionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionStatus.
func (in *ExtensionStatus) DeepCopy() *ExtensionStatus {
	if in == nil {
		return nil
	}
	out := new(ExtensionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileEvent) DeepCopyInto(out *FileEvent) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.SeenFiles != nil {
		in, out := &in.SeenFiles, &out.SeenFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileEvent.
func (in *FileEvent) DeepCopy() *FileEvent {
	if in == nil {
		return nil
	}
	out := new(FileEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileWatch) DeepCopyInto(out *FileWatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileWatch.
func (in *FileWatch) DeepCopy() *FileWatch {
	if in == nil {
		return nil
	}
	out := new(FileWatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FileWatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileWatchList) DeepCopyInto(out *FileWatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FileWatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileWatchList.
func (in *FileWatchList) DeepCopy() *FileWatchList {
	if in == nil {
		return nil
	}
	out := new(FileWatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FileWatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileWatchSpec) DeepCopyInto(out *FileWatchSpec) {
	*out = *in
	if in.WatchedPaths != nil {
		in, out := &in.WatchedPaths, &out.WatchedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ignores != nil {
		in, out := &in.Ignores, &out.Ignores
		*out = make([]IgnoreDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisableSource != nil {
		in, out := &in.DisableSource, &out.DisableSource
		*out = new(DisableSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileWatchSpec.
func (in *FileWatchSpec) DeepCopy() *FileWatchSpec {
	if in == nil {
		return nil
	}
	out := new(FileWatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileWatchStatus) DeepCopyInto(out *FileWatchStatus) {
	*out = *in
	in.MonitorStartTime.DeepCopyInto(&out.MonitorStartTime)
	in.LastEventTime.DeepCopyInto(&out.LastEventTime)
	if in.FileEvents != nil {
		in, out := &in.FileEvents, &out.FileEvents
		*out = make([]FileEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisableStatus != nil {
		in, out := &in.DisableStatus, &out.DisableStatus
		*out = new(DisableStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileWatchStatus.
func (in *FileWatchStatus) DeepCopy() *FileWatchStatus {
	if in == nil {
		return nil
	}
	out := new(FileWatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPGetAction) DeepCopyInto(out *HTTPGetAction) {
	*out = *in
	if in.HTTPHeaders != nil {
		in, out := &in.HTTPHeaders, &out.HTTPHeaders
		*out = make([]HTTPHeader, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPGetAction.
func (in *HTTPGetAction) DeepCopy() *HTTPGetAction {
	if in == nil {
		return nil
	}
	out := new(HTTPGetAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHeader) DeepCopyInto(out *HTTPHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHeader.
func (in *HTTPHeader) DeepCopy() *HTTPHeader {
	if in == nil {
		return nil
	}
	out := new(HTTPHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Handler) DeepCopyInto(out *Handler) {
	*out = *in
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(ExecAction)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPGet != nil {
		in, out := &in.HTTPGet, &out.HTTPGet
		*out = new(HTTPGetAction)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPSocket != nil {
		in, out := &in.TCPSocket, &out.TCPSocket
		*out = new(TCPSocketAction)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Handler.
func (in *Handler) DeepCopy() *Handler {
	if in == nil {
		return nil
	}
	out := new(Handler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnoreDef) DeepCopyInto(out *IgnoreDef) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnoreDef.
func (in *IgnoreDef) DeepCopy() *IgnoreDef {
	if in == nil {
		return nil
	}
	out := new(IgnoreDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectSelector) DeepCopyInto(out *ObjectSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectSelector.
func (in *ObjectSelector) DeepCopy() *ObjectSelector {
	if in == nil {
		return nil
	}
	out := new(ObjectSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Probe) DeepCopyInto(out *Probe) {
	*out = *in
	in.Handler.DeepCopyInto(&out.Handler)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Probe.
func (in *Probe) DeepCopy() *Probe {
	if in == nil {
		return nil
	}
	out := new(Probe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartOnSpec) DeepCopyInto(out *RestartOnSpec) {
	*out = *in
	if in.FileWatches != nil {
		in, out := &in.FileWatches, &out.FileWatches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UIButtons != nil {
		in, out := &in.UIButtons, &out.UIButtons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartOnSpec.
func (in *RestartOnSpec) DeepCopy() *RestartOnSpec {
	if in == nil {
		return nil
	}
	out := new(RestartOnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Session) DeepCopyInto(out *Session) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Session.
func (in *Session) DeepCopy() *Session {
	if in == nil {
		return nil
	}
	out := new(Session)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Session) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionCISpec) DeepCopyInto(out *SessionCISpec) {
	*out = *in
	if in.K8sGracePeriod != nil {
		in, out := &in.K8sGracePeriod, &out.K8sGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ReadinessTimeout != nil {
		in, out := &in.ReadinessTimeout, &out.ReadinessTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionCISpec.
func (in *SessionCISpec) DeepCopy() *SessionCISpec {
	if in == nil {
		return nil
	}
	out := new(SessionCISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionList) DeepCopyInto(out *SessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Session, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionList.
func (in *SessionList) DeepCopy() *SessionList {
	if in == nil {
		return nil
	}
	out := new(SessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionSpec) DeepCopyInto(out *SessionSpec) {
	*out = *in
	if in.CI != nil {
		in, out := &in.CI, &out.CI
		*out = new(SessionCISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionSpec.
func (in *SessionSpec) DeepCopy() *SessionSpec {
	if in == nil {
		return nil
	}
	out := new(SessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionStatus) DeepCopyInto(out *SessionStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]Target, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionStatus.
func (in *SessionStatus) DeepCopy() *SessionStatus {
	if in == nil {
		return nil
	}
	out := new(SessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartOnSpec) DeepCopyInto(out *StartOnSpec) {
	*out = *in
	in.StartAfter.DeepCopyInto(&out.StartAfter)
	if in.UIButtons != nil {
		in, out := &in.UIButtons, &out.UIButtons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartOnSpec.
func (in *StartOnSpec) DeepCopy() *StartOnSpec {
	if in == nil {
		return nil
	}
	out := new(StartOnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateSource) DeepCopyInto(out *StateSource) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ConfigMapStateSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateSource.
func (in *StateSource) DeepCopy() *StateSource {
	if in == nil {
		return nil
	}
	out := new(StateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopOnSpec) DeepCopyInto(out *StopOnSpec) {
	*out = *in
	if in.UIButtons != nil {
		in, out := &in.UIButtons, &out.UIButtons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopOnSpec.
func (in *StopOnSpec) DeepCopy() *StopOnSpec {
	if in == nil {
		return nil
	}
	out := new(StopOnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPSocketAction) DeepCopyInto(out *TCPSocketAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPSocketAction.
func (in *TCPSocketAction) DeepCopy() *TCPSocketAction {
	if in == nil {
		return nil
	}
	out := new(TCPSocketAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetState) DeepCopyInto(out *TargetState) {
	*out = *in
	if in.Waiting != nil {
		in, out := &in.Waiting, &out.Waiting
		*out = new(TargetStateWaiting)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(TargetStateActive)
		(*in).DeepCopyInto(*out)
	}
	if in.Terminated != nil {
		in, out := &in.Terminated, &out.Terminated
		*out = new(TargetStateTerminated)
		(*in).DeepCopyInto(*out)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(TargetStateDisabled)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetState.
func (in *TargetState) DeepCopy() *TargetState {
	if in == nil {
		return nil
	}
	out := new(TargetState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStateActive) DeepCopyInto(out *TargetStateActive) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.LastReadyTime.DeepCopyInto(&out.LastReadyTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStateActive.
func (in *TargetStateActive) DeepCopy() *TargetStateActive {
	if in == nil {
		return nil
	}
	out := new(TargetStateActive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStateDisabled) DeepCopyInto(out *TargetStateDisabled) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStateDisabled.
func (in *TargetStateDisabled) DeepCopy() *TargetStateDisabled {
	if in == nil {
		return nil
	}
	out := new(TargetStateDisabled)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStateTerminated) DeepCopyInto(out *TargetStateTerminated) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.FinishTime.DeepCopyInto(&out.FinishTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStateTerminated.
func (in *TargetStateTerminated) DeepCopy() *TargetStateTerminated {
	if in == nil {
		return nil
	}
	out := new(TargetStateTerminated)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStateWaiting) DeepCopyInto(out *TargetStateWaiting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStateWaiting.
func (in *TargetStateWaiting) DeepCopy() *TargetStateWaiting {
	if in == nil {
		return nil
	}
	out := new(TargetStateWaiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiltBuild) DeepCopyInto(out *TiltBuild) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiltBuild.
func (in *TiltBuild) DeepCopy() *TiltBuild {
	if in == nil {
		return nil
	}
	out := new(TiltBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tiltfile) DeepCopyInto(out *Tiltfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tiltfile.
func (in *Tiltfile) DeepCopy() *Tiltfile {
	if in == nil {
		return nil
	}
	out := new(Tiltfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tiltfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiltfileList) DeepCopyInto(out *TiltfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tiltfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiltfileList.
func (in *TiltfileList) DeepCopy() *TiltfileList {
	if in == nil {
		return nil
	}
	out := new(TiltfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TiltfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiltfileSpec) DeepCopyInto(out *TiltfileSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RestartOn != nil {
		in, out := &in.RestartOn, &out.RestartOn
		*out = new(RestartOnSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StopOn != nil {
		in, out := &in.StopOn, &out.StopOn
		*out = new(StopOnSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiltfileSpec.
func (in *TiltfileSpec) DeepCopy() *TiltfileSpec {
	if in == nil {
		return nil
	}
	out := new(TiltfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiltfileStateRunning) DeepCopyInto(out *TiltfileStateRunning) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiltfileStateRunning.
func (in *TiltfileStateRunning) DeepCopy() *TiltfileStateRunning {
	if in == nil {
		return nil
	}
	out := new(TiltfileStateRunning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiltfileStateTerminated) DeepCopyInto(out *TiltfileStateTerminated) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiltfileStateTerminated.
func (in *TiltfileStateTerminated) DeepCopy() *TiltfileStateTerminated {
	if in == nil {
		return nil
	}
	out := new(TiltfileStateTerminated)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiltfileStateWaiting) DeepCopyInto(out *TiltfileStateWaiting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiltfileStateWaiting.
func (in *TiltfileStateWaiting) DeepCopy() *TiltfileStateWaiting {
	if in == nil {
		return nil
	}
	out := new(TiltfileStateWaiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiltfileStatus) DeepCopyInto(out *TiltfileStatus) {
	*out = *in
	if in.Waiting != nil {
		in, out := &in.Waiting, &out.Waiting
		*out = new(TiltfileStateWaiting)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(TiltfileStateRunning)
		(*in).DeepCopyInto(*out)
	}
	if in.Terminated != nil {
		in, out := &in.Terminated, &out.Terminated
		*out = new(TiltfileStateTerminated)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiltfileStatus.
func (in *TiltfileStatus) DeepCopy() *TiltfileStatus {
	if in == nil {
		return nil
	}
	out := new(TiltfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToggleButton) DeepCopyInto(out *ToggleButton) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToggleButton.
func (in *ToggleButton) DeepCopy() *ToggleButton {
	if in == nil {
		return nil
	}
	out := new(ToggleButton)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToggleButton) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToggleButtonList) DeepCopyInto(out *ToggleButtonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToggleButton, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToggleButtonList.
func (in *ToggleButtonList) DeepCopy() *ToggleButtonList {
	if in == nil {
		return nil
	}
	out := new(ToggleButtonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToggleButtonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToggleButtonSpec) DeepCopyInto(out *ToggleButtonSpec) {
	*out = *in
	out.Location = in.Location
	out.On = in.On
	out.Off = in.Off
	in.StateSource.DeepCopyInto(&out.StateSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToggleButtonSpec.
func (in *ToggleButtonSpec) DeepCopy() *ToggleButtonSpec {
	if in == nil {
		return nil
	}
	out := new(ToggleButtonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToggleButtonStateSpec) DeepCopyInto(out *ToggleButtonStateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToggleButtonStateSpec.
func (in *ToggleButtonStateSpec) DeepCopy() *ToggleButtonStateSpec {
	if in == nil {
		return nil
	}
	out := new(ToggleButtonStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToggleButtonStatus) DeepCopyInto(out *ToggleButtonStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToggleButtonStatus.
func (in *ToggleButtonStatus) DeepCopy() *ToggleButtonStatus {
	if in == nil {
		return nil
	}
	out := new(ToggleButtonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIBoolInputSpec) DeepCopyInto(out *UIBoolInputSpec) {
	*out = *in
	if in.TrueString != nil {
		in, out := &in.TrueString, &out.TrueString
		*out = new(string)
		**out = **in
	}
	if in.FalseString != nil {
		in, out := &in.FalseString, &out.FalseString
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIBoolInputSpec.
func (in *UIBoolInputSpec) DeepCopy() *UIBoolInputSpec {
	if in == nil {
		return nil
	}
	out := new(UIBoolInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIBoolInputStatus) DeepCopyInto(out *UIBoolInputStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIBoolInputStatus.
func (in *UIBoolInputStatus) DeepCopy() *UIBoolInputStatus {
	if in == nil {
		return nil
	}
	out := new(UIBoolInputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIBuildRunning) DeepCopyInto(out *UIBuildRunning) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIBuildRunning.
func (in *UIBuildRunning) DeepCopy() *UIBuildRunning {
	if in == nil {
		return nil
	}
	out := new(UIBuildRunning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIBuildTerminated) DeepCopyInto(out *UIBuildTerminated) {
	*out = *in
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.FinishTime.DeepCopyInto(&out.FinishTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIBuildTerminated.
func (in *UIBuildTerminated) DeepCopy() *UIBuildTerminated {
	if in == nil {
		return nil
	}
	out := new(UIBuildTerminated)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIButton) DeepCopyInto(out *UIButton) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIButton.
func (in *UIButton) DeepCopy() *UIButton {
	if in == nil {
		return nil
	}
	out := new(UIButton)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UIButton) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIButtonList) DeepCopyInto(out *UIButtonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UIButton, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIButtonList.
func (in *UIButtonList) DeepCopy() *UIButtonList {
	if in == nil {
		return nil
	}
	out := new(UIButtonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UIButtonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIButtonSpec) DeepCopyInto(out *UIButtonSpec) {
	*out = *in
	out.Location = in.Location
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]UIInputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIButtonSpec.
func (in *UIButtonSpec) DeepCopy() *UIButtonSpec {
	if in == nil {
		return nil
	}
	out := new(UIButtonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIButtonStatus) DeepCopyInto(out *UIButtonStatus) {
	*out = *in
	in.LastClickedAt.DeepCopyInto(&out.LastClickedAt)
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]UIInputStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIButtonStatus.
func (in *UIButtonStatus) DeepCopy() *UIButtonStatus {
	if in == nil {
		return nil
	}
	out := new(UIButtonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIChoiceInputSpec) DeepCopyInto(out *UIChoiceInputSpec) {
	*out = *in
	if in.Choices != nil {
		in, out := &in.Choices, &out.Choices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIChoiceInputSpec.
func (in *UIChoiceInputSpec) DeepCopy() *UIChoiceInputSpec {
	if in == nil {
		return nil
	}
	out := new(UIChoiceInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIChoiceInputStatus) DeepCopyInto(out *UIChoiceInputStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIChoiceInputStatus.
func (in *UIChoiceInputStatus) DeepCopy() *UIChoiceInputStatus {
	if in == nil {
		return nil
	}
	out := new(UIChoiceInputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIComponentLocation) DeepCopyInto(out *UIComponentLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIComponentLocation.
func (in *UIComponentLocation) DeepCopy() *UIComponentLocation {
	if in == nil {
		return nil
	}
	out := new(UIComponentLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIComponentLocationResource) DeepCopyInto(out *UIComponentLocationResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIComponentLocationResource.
func (in *UIComponentLocationResource) DeepCopy() *UIComponentLocationResource {
	if in == nil {
		return nil
	}
	out := new(UIComponentLocationResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIFeatureFlag) DeepCopyInto(out *UIFeatureFlag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIFeatureFlag.
func (in *UIFeatureFlag) DeepCopy() *UIFeatureFlag {
	if in == nil {
		return nil
	}
	out := new(UIFeatureFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIHiddenInputSpec) DeepCopyInto(out *UIHiddenInputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIHiddenInputSpec.
func (in *UIHiddenInputSpec) DeepCopy() *UIHiddenInputSpec {
	if in == nil {
		return nil
	}
	out := new(UIHiddenInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIHiddenInputStatus) DeepCopyInto(out *UIHiddenInputStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIHiddenInputStatus.
func (in *UIHiddenInputStatus) DeepCopy() *UIHiddenInputStatus {
	if in == nil {
		return nil
	}
	out := new(UIHiddenInputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIInputSpec) DeepCopyInto(out *UIInputSpec) {
	*out = *in
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(UITextInputSpec)
		**out = **in
	}
	if in.Bool != nil {
		in, out := &in.Bool, &out.Bool
		*out = new(UIBoolInputSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(UIHiddenInputSpec)
		**out = **in
	}
	if in.Choice != nil {
		in, out := &in.Choice, &out.Choice
		*out = new(UIChoiceInputSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIInputSpec.
func (in *UIInputSpec) DeepCopy() *UIInputSpec {
	if in == nil {
		return nil
	}
	out := new(UIInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIInputStatus) DeepCopyInto(out *UIInputStatus) {
	*out = *in
	if in.Text != nil {
		in, out := &in.Text, &out.Text
		*out = new(UITextInputStatus)
		**out = **in
	}
	if in.Bool != nil {
		in, out := &in.Bool, &out.Bool
		*out = new(UIBoolInputStatus)
		**out = **in
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(UIHiddenInputStatus)
		**out = **in
	}
	if in.Choice != nil {
		in, out := &in.Choice, &out.Choice
		*out = new(UIChoiceInputStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIInputStatus.
func (in *UIInputStatus) DeepCopy() *UIInputStatus {
	if in == nil {
		return nil
	}
	out := new(UIInputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResource) DeepCopyInto(out *UIResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResource.
func (in *UIResource) DeepCopy() *UIResource {
	if in == nil {
		return nil
	}
	out := new(UIResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UIResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceCompose) DeepCopyInto(out *UIResourceCompose) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceCompose.
func (in *UIResourceCompose) DeepCopy() *UIResourceCompose {
	if in == nil {
		return nil
	}
	out := new(UIResourceCompose)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceCondition) DeepCopyInto(out *UIResourceCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceCondition.
func (in *UIResourceCondition) DeepCopy() *UIResourceCondition {
	if in == nil {
		return nil
	}
	out := new(UIResourceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceKubernetes) DeepCopyInto(out *UIResourceKubernetes) {
	*out = *in
	in.PodCreationTime.DeepCopyInto(&out.PodCreationTime)
	in.PodUpdateStartTime.DeepCopyInto(&out.PodUpdateStartTime)
	if in.DisplayNames != nil {
		in, out := &in.DisplayNames, &out.DisplayNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceKubernetes.
func (in *UIResourceKubernetes) DeepCopy() *UIResourceKubernetes {
	if in == nil {
		return nil
	}
	out := new(UIResourceKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceLink) DeepCopyInto(out *UIResourceLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceLink.
func (in *UIResourceLink) DeepCopy() *UIResourceLink {
	if in == nil {
		return nil
	}
	out := new(UIResourceLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceList) DeepCopyInto(out *UIResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UIResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceList.
func (in *UIResourceList) DeepCopy() *UIResourceList {
	if in == nil {
		return nil
	}
	out := new(UIResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UIResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceLocal) DeepCopyInto(out *UIResourceLocal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceLocal.
func (in *UIResourceLocal) DeepCopy() *UIResourceLocal {
	if in == nil {
		return nil
	}
	out := new(UIResourceLocal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceSpec) DeepCopyInto(out *UIResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceSpec.
func (in *UIResourceSpec) DeepCopy() *UIResourceSpec {
	if in == nil {
		return nil
	}
	out := new(UIResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceStateWaiting) DeepCopyInto(out *UIResourceStateWaiting) {
	*out = *in
	if in.On != nil {
		in, out := &in.On, &out.On
		*out = make([]UIResourceStateWaitingOnRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceStateWaiting.
func (in *UIResourceStateWaiting) DeepCopy() *UIResourceStateWaiting {
	if in == nil {
		return nil
	}
	out := new(UIResourceStateWaiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceStateWaitingOnRef) DeepCopyInto(out *UIResourceStateWaitingOnRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceStateWaitingOnRef.
func (in *UIResourceStateWaitingOnRef) DeepCopy() *UIResourceStateWaitingOnRef {
	if in == nil {
		return nil
	}
	out := new(UIResourceStateWaitingOnRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceStatus) DeepCopyInto(out *UIResourceStatus) {
	*out = *in
	in.LastDeployTime.DeepCopyInto(&out.LastDeployTime)
	if in.BuildHistory != nil {
		in, out := &in.BuildHistory, &out.BuildHistory
		*out = make([]UIBuildTerminated, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentBuild != nil {
		in, out := &in.CurrentBuild, &out.CurrentBuild
		*out = new(UIBuildRunning)
		(*in).DeepCopyInto(*out)
	}
	in.PendingBuildSince.DeepCopyInto(&out.PendingBuildSince)
	if in.EndpointLinks != nil {
		in, out := &in.EndpointLinks, &out.EndpointLinks
		*out = make([]UIResourceLink, len(*in))
		copy(*out, *in)
	}
	if in.K8sResourceInfo != nil {
		in, out := &in.K8sResourceInfo, &out.K8sResourceInfo
		*out = new(UIResourceKubernetes)
		(*in).DeepCopyInto(*out)
	}
	if in.ComposeResourceInfo != nil {
		in, out := &in.ComposeResourceInfo, &out.ComposeResourceInfo
		*out = new(UIResourceCompose)
		**out = **in
	}
	if in.LocalResourceInfo != nil {
		in, out := &in.LocalResourceInfo, &out.LocalResourceInfo
		*out = new(UIResourceLocal)
		**out = **in
	}
	if in.Specs != nil {
		in, out := &in.Specs, &out.Specs
		*out = make([]UIResourceTargetSpec, len(*in))
		copy(*out, *in)
	}
	in.DisableStatus.DeepCopyInto(&out.DisableStatus)
	if in.Waiting != nil {
		in, out := &in.Waiting, &out.Waiting
		*out = new(UIResourceStateWaiting)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]UIResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceStatus.
func (in *UIResourceStatus) DeepCopy() *UIResourceStatus {
	if in == nil {
		return nil
	}
	out := new(UIResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIResourceTargetSpec) DeepCopyInto(out *UIResourceTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIResourceTargetSpec.
func (in *UIResourceTargetSpec) DeepCopy() *UIResourceTargetSpec {
	if in == nil {
		return nil
	}
	out := new(UIResourceTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UISession) DeepCopyInto(out *UISession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UISession.
func (in *UISession) DeepCopy() *UISession {
	if in == nil {
		return nil
	}
	out := new(UISession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UISession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UISessionList) DeepCopyInto(out *UISessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UISession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UISessionList.
func (in *UISessionList) DeepCopy() *UISessionList {
	if in == nil {
		return nil
	}
	out := new(UISessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UISessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UISessionSpec) DeepCopyInto(out *UISessionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UISessionSpec.
func (in *UISessionSpec) DeepCopy() *UISessionSpec {
	if in == nil {
		return nil
	}
	out := new(UISessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UISessionStatus) DeepCopyInto(out *UISessionStatus) {
	*out = *in
	if in.FeatureFlags != nil {
		in, out := &in.FeatureFlags, &out.FeatureFlags
		*out = make([]UIFeatureFlag, len(*in))
		copy(*out, *in)
	}
	out.RunningTiltBuild = in.RunningTiltBuild
	out.VersionSettings = in.VersionSettings
	in.TiltStartTime.DeepCopyInto(&out.TiltStartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UISessionStatus.
func (in *UISessionStatus) DeepCopy() *UISessionStatus {
	if in == nil {
		return nil
	}
	out := new(UISessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UITextInputSpec) DeepCopyInto(out *UITextInputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UITextInputSpec.
func (in *UITextInputSpec) DeepCopy() *UITextInputSpec {
	if in == nil {
		return nil
	}
	out := new(UITextInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UITextInputStatus) DeepCopyInto(out *UITextInputStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UITextInputStatus.
func (in *UITextInputStatus) DeepCopy() *UITextInputStatus {
	if in == nil {
		return nil
	}
	out := new(UITextInputStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionSettings) DeepCopyInto(out *VersionSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionSettings.
func (in *VersionSettings) DeepCopy() *VersionSettings {
	if in == nil {
		return nil
	}
	out := new(VersionSettings)
	in.DeepCopyInto(out)
	return out
}
