VERSION 0.8

buildkite:
    ARG image=cache.defn.run:5000/dfd:buildkite
    FROM ghcr.io/buildkite/agent-stack-k8s/agent:0.7.0

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    RUN git clone --mirror -v -- https://github.com/defn/dev.git ${BUILDKITE_GIT_MIRRORS_PATH}/https---github-com-defn-dev-git
    RUN --no-cache cd ${BUILDKITE_GIT_MIRRORS_PATH}/https---github-com-defn-dev-git && git fetch origin
    SAVE IMAGE --push ${image}

class-init:
    ARG image=cache.defn.run:5000/dfd:class
    ARG vsextensions=vscodevim.vim jnoortheen.nix-ide hashicorp.terraform golang.go esbenp.prettier-vscode bazelbuild.vscode-bazel cuelang.cue pbkit.vscode-pbkit marp-team.marp-vscode tailscale.vscode-tailscale geequlim.godot-tools alfish.godot-files ms-python.python
    FROM cache.defn.run:5000/dfd:base

    CACHE /home/ubuntu/work

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    RUN sudo chown ubuntu:ubuntu /home/ubuntu/work && chmod 755 /home/ubuntu/work
    COPY script/800-defn-dev .
    RUN ./800-defn-dev && rm -f ./800-defn-dev
    RUN bash -c 'source .bash_profile && for e in ${vsextensions}; do bin/nix/code-server serve-local --force --install-extension $e; done'
    RUN bash -c 'source .bash_profile && cd ~/m && ~/bin/persist-cache && go install golang.org/x/tools/gopls@latest && go install honnef.co/go/tools/cmd/staticcheck@latest && cd && git checkout .'

    SAVE IMAGE --push ${image}-latest
    SAVE IMAGE --push ${image}-buildkite-latest

class-latest:
    ARG image=cache.defn.run:5000/dfd:class-latest
    FROM ${image}

    CACHE /home/ubuntu/work

    RUN --no-cache git config --global user.email "you@example.com" && git config --global user.name "Your Name" && git pull
    RUN bash -c 'source .bash_profile && make home && git checkout .'

    SAVE IMAGE --push ${image}

class-buildkite-latest:
    ARG image=cache.defn.run:5000/dfd:class-buildkite-latest
    FROM ${image}

    RUN --no-cache git config --global user.email "you@example.com" && git config --global user.name "Your Name" && git pull
    RUN bash -c 'source .bash_profile && bin/persist-cache && cd m && b build && cd && git checkout .'

    SAVE IMAGE --push ${image}
