VERSION 0.8

buildkite:
    ARG image=cache.defn.run:5000/dfd:buildkite
    FROM ghcr.io/buildkite/agent-stack-k8s/agent:0.7.0

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    RUN git clone --mirror -v -- https://github.com/defn/dev.git ${BUILDKITE_GIT_MIRRORS_PATH}/https---github-com-defn-dev-git
    RUN --no-cache cd ${BUILDKITE_GIT_MIRRORS_PATH}/https---github-com-defn-dev-git && git fetch origin
    SAVE IMAGE --push ${image}

class:
    ARG image=cache.defn.run:5000/dfd:class
    BUILD +build-class-core --image=${image}
    BUILD +build-class-core --image=${image}-latest

class-latest:
    ARG image=cache.defn.run:5000/dfd:class
    BUILD +build-class-latest --image=${image}-latest

build-class-core:
    ARG image
    BUILD +image-class-core --image=${image}

build-class-latest:
    ARG image
    BUILD +image-class-latest --image=${image}

image-class-core:
    ARG image
    FROM +core-class

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    SAVE IMAGE --push ${image}

image-class-latest:
    ARG image
    FROM +latest-class

    SAVE IMAGE --push ${image}

core-class:
    FROM cache.defn.run:5000/dfd:base

    CACHE /home/ubuntu/work
    RUN sudo chown ubuntu:ubuntu /home/ubuntu/work && chmod 755 /home/ubuntu/work

    COPY script/800-defn-dev .
    RUN ./800-defn-dev && rm -f ./800-defn-dev

    RUN bash -c 'source .bash_profile && for e in vscodevim.vim jnoortheen.nix-ide hashicorp.terraform golang.go esbenp.prettier-vscode bazelbuild.vscode-bazel cuelang.cue marp-team.marp-vscode; do bin/nix/code-server serve-local --force --install-extension $e; done'
    RUN bash -c 'source .bash_profile && cd ~/m && ~/bin/persist-cache && go install golang.org/x/tools/gopls@latest && go install honnef.co/go/tools/cmd/staticcheck@latest && cd && git checkout .'

latest-class:
    FROM cache.defn.run:5000/dfd:class-latest

    CACHE /home/ubuntu/work

    RUN --no-cache git config --global user.email "you@example.com" && git config --global user.name "Your Name" && git pull
    RUN bash -c 'source .bash_profile && (set +f; ls -ltrhd ~/bin/nix/.head* || true) && make home && git checkout .'
