#!/usr/bin/env python

load("ext://restart_process", "custom_build_with_restart")

# local k8s
allow_k8s_contexts('dfd')

# local registry
default_registry("169.254.32.1:5000")

local_resource(name="tutorial", cmd="cue eval --out json -e html | jq -r . > tutorial.html", deps=["tutorial.cue"])

# hook build
local_resource(name="hook-config", cmd="./hooks/hook.sh --config", deps=["./hooks"])

# hook initial deploy
k8s_yaml(local("bash -c \"cat deploy.yaml | sed \\\"s#NAMESPACE#$(echo $HOSTNAME | cut -d- -f1-3)#\\\"\""))

# hook service selected from deploy
k8s_resource("hook", resource_deps=["hook-config"])

# hook updates when hook updates
custom_build_with_restart(
    ref="hook",
    command="make build image=$EXPECTED_REF",
    entrypoint=["/shell-operator"],
    deps=["./hooks"],
    trigger=["./hooks"],
    live_update=[
        sync("./hooks", "/hooks"),
    ],
)
