# get a shell in container
shell:
    docker compose exec home bash

# run container
up:
    docker compose pull
    docker compose up -d --remove-orphans
    docker compose exec home tailscale up --ssh --hostname "$(hostname | cut -d . -f1)-dev"