# get a shell in container
shell:
    docker compose exec home bash

# run container
up:
    docker compose pull
    docker compose up -d --remove-orphans
    docker compose exec home sudo tailscale up --ssh --hostname "$(hostname | cut -d . -f1)-dev"
    docker compose exec home tailscale ip

# stop container
down:
    docker compose down
