# get a shell in container
shell:
    docker compose exec home bash

# run container
up:
    mise run activate dev
    mise run start dev
    docker compose exec home sudo tailscale up --ssh --hostname "$(hostname | cut -d . -f1)-dev"
    docker compose exec home tailscale ip
