VERSION 0.7

buildkite:
    ARG image=cache.defn.run:5000/dfd:buildkite
    FROM ghcr.io/buildkite/agent-stack-k8s/agent:0.7.0

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    RUN --no-cache git clone --mirror -v -- https://github.com/defn/dev.git ${BUILDKITE_GIT_MIRRORS_PATH}/https---github-com-defn-dev-git
    SAVE IMAGE --push ${image}

class:
    ARG image=cache.defn.run:5000/dfd:class
    BUILD +build-class --image=${image}

build-class:
    ARG image
    BUILD +image-class --image=${image}

image-class:
    ARG image
    FROM +core-class

    ENV BUILDKITE_GIT_MIRRORS_PATH=/cache/git
    ENV BUILDKITE_GIT_MIRRORS_SKIP_UPDATE=1

    SAVE IMAGE --push ${image}

core-class:
    FROM quay.io/defn/dev:latest

    COPY script/800-defn-dev script/999-update .
    RUN ./800-defn-dev

    RUN bash -c 'source .bashrc && ~/bin/persist-cache && make nix home'
    RUN bash -c 'source .bashrc && for e in vscodevim.vim jnoortheen.nix-ide hashicorp.terraform golang.go esbenp.prettier-vscode bazelbuild.vscode-bazel cuelang.cue marp-team.marp-vscode; do bin/nix/code-server serve-local --force --install-extension $e; done'
    RUN bash -c 'source .bashrc && cd ~/m && ~/bin/persist-cache && go install golang.org/x/tools/gopls@latest && go install honnef.co/go/tools/cmd/staticcheck@latest && cd && git checkout .'

    RUN --no-cache git pull
    RUN bash -c 'source .bashrc && make home'