// Generated by Wrangler by running `wrangler types`

interface Env {
  kv: KVNamespace;
  mydo: DurableObjectNamespace<
    import("./dist/_worker.js/index").MyDurableObject
  >;
  bucket: R2Bucket;
  db: D1Database;
  ASSETS: Fetcher;
}
