# https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/ubuntu.html
install-common:
    sudo mkdir --parents --mode=0755 /etc/apt/keyrings
    wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/6.2/ubuntu noble main" | sudo tee /etc/apt/sources.list.d/amdgpu.list
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.2 noble main" | sudo tee --append /etc/apt/sources.list.d/rocm.list
    echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
    sudo apt update

install-reboot:
    just install-common
    sudo apt install -y amdgpu-dkms

install:
    just install-common
    sudo apt install -y libstdc++-10-dev
    sudo apt install -y rocm
    /usr/bin/python3 -m venv common
    git submodule update --init
    source common/bin/activate && pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0
    source common/bin/activate && pip install -r repo/requirements.txt

reinstall:
    rm -rf common
    just install

# --cpu
run *args:
    source common/bin/activate && cd repo && python main.py {{args}}

sd15:
    wget -P repo/models/checkpoints https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt

cascade:
    wget -P repo/models/checkpoints https://huggingface.co/stabilityai/stable-cascade/tree/main/comfyui_checkpoints
    wget -P repo/models/checkpoints https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_b.safetensors
    wget -P repo/models/checkpoints https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_c.safetensors
