common:
    sudo apt install libstdc++-10-dev
    /usr/bin/python3 -m venv common
    common/bin/pip install -r repo/requirements.txt

run *args:
    cd repo && ../common/bin/python main.py {{args}}

sd15:
    wget -P repo/models/checkpoints https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt

cascade:
    wget -P repo/models/checkpoints https://huggingface.co/stabilityai/stable-cascade/tree/main/comfyui_checkpoints
    wget -P repo/models/checkpoints https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_b.safetensors
    wget -P repo/models/checkpoints https://huggingface.co/stabilityai/stable-cascade/resolve/main/comfyui_checkpoints/stable_cascade_stage_c.safetensors
