#!/usr/bin/env python

load("../../common/Tiltfile", "main")

load('ext://uibutton', 'cmd_button', 'location')

main(
    app_entrypoint=["/cli", "api"],
    app_release="gen/cli.bin",
    app_build="../../bazel-bin/src/dev/dev_/dev",
    host="src--dev",
    context="meh",
    registry="quay.io/defn"
)

cmd_button(name='www',
           argv=["open", "http://127.0.0.1:19999"],
           location=location.NAV,
           text='website',
           icon_name='support_agent')

cmd_button(name='app',
           argv=["open", "http://127.0.0.1:20000"],
           location=location.NAV,
           text='application',
           icon_name='support_agent')

local_resource(
    "forward-www",
    serve_cmd=[
        "bash",
        "-c",
        """
            echo http://127.0.0.1:19999
            kubectl port-forward service/www -n src--dev 19999:80
        """,
    ]
)

local_resource(
    "forward-app",
    serve_cmd=[
        "bash",
        "-c",
        """
            echo http://127.0.0.1:20000
            kubectl port-forward service/app -n src--dev 20000:80
        """,
    ]
)
