#!/usr/bin/env python

load("../../common/Tiltfile", "main")

main(
    context="coder-amanibhavam-district0-cluster",
    registry="cache.defn.run:5000",
    app_service="api",
    app_entrypoint="/cli",
    app_build="../../bazel-bin/src/dev/dev_/dev",
    app_release="gen/cli.bin",
)
