#!/usr/bin/env bash

set -efu -o pipefail

n=$(($(nproc) / 2))
((n < 8)) && n=8

function fork {
	local type="$1"
	shift

	local r="$1"
	shift


	case "${type}" in
		ec2-instance)
			run="aws --region $r ec2 describe-instances"
			${run} | jq --arg region "$r" --arg type "$type" \
				'.Reservations[].Instances | map({(.InstanceId): .}) | add | {($region): {($type): .}}' \
				>"${tmp}/$type-$r.json" &

			throttle "${run}"
			;;
		ec2-volume)
			type="volume"
			run="aws --region $r ec2 describe-volumes"
			${run} | jq --arg region "$r" --arg type "$type" \
				'.Volumes | map({(.VolumeId): .}) | add | {($region): {($type): .}}' \
				>"${tmp}/$type-$r.json" &

			throttle "${run}"
			;;
		*)
			echo "ERROR: unknown command: ${run} ($r)"
			return 1
			;;
	esac
}

function throttle {
	if (($(jobs -r | wc -l | awk '{print $1}') >= n)); then
		echo "INFO: waiting... $@" 1>&2
		wait -n
	else
		echo "INFO: $(jobs -r | wc -l | awk '{print $1}')/$n" 1>&2
	fi
}

function main {
	cd "${MISE_ORIGINAL_CWD}"

	if [[ $# == 0 ]]; then
		set -- $(aws ec2 describe-regions | jq -r '.Regions[].RegionName')
	fi

	export tmp="$(mktemp -d ${TEMPDIR:=/tmp}/XXXXXX)"
	trap 'rm -rf "${tmp}"' EXIT

	for r in "$@"; do
		fork ec2-instance "$r"
		fork ec2-volume "$r"
	done
	wait

	(
		set +f
		if ! cat ${tmp}/*.json | jq -s 'add | {aws: .}' >/dev/null; then
			cd "${tmp}"
			bash -il
		fi
	)
}

main "$@"
