#!/usr/bin/env bash

set -efu -o pipefail

n=$(($(nproc) / 2))
((n < 8)) && n=8

function fork {
	local cmd="$1"
	shift

	local r="$1"
	shift


	case "${cmd}" in
		ec2)
			run="aws --region $r ec2 describe-instances"
			${run} | jq --arg region "$r" \
				'.Reservations[].Instances | map({(.InstanceId): .}) | add | {($region): {instance: .}}' \
				>"${tmp}/$r.json" &

			throttle "${run}"
			;;
		*)
			echo "ERROR: unknown command: ${run} ($r)"
			return 1
			;;
	esac
}

function throttle {
	if (($(jobs -r | wc -l | awk '{print $1}') >= n)); then
		echo "INFO: waiting... $@" 1>&2
		wait -n
	else
		echo "INFO: $(jobs -r | wc -l | awk '{print $1}')/$n" 1>&2
	fi
}

function main {
	cd "${MISE_ORIGINAL_CWD}"

	if [[ $# == 0 ]]; then
		set -- $(aws ec2 describe-regions | jq -r '.Regions[].RegionName')
	fi

	export tmp="$(mktemp -d ${TEMPDIR:=/tmp}/XXXXXX)"
	trap 'rm -rf "${tmp}"' EXIT

	for r in "$@"; do
		fork ec2 "$r"
	done
	wait

	(
		set +f
		cat ${tmp}/*.json | jq -s 'add | {aws: .}'
	)
}

main "$@"
