// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package zoo

type Food struct {
	Name string `json:"name"`

	Cost float64 `json:"cost"`
}

type Dog struct {
	Age int64 `json:"age"`

	Name string `json:"name"`

	Snack Food `json:"snack"`
}
