#!/usr/bin/env bash

set -efu -o pipefail

function main {
	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		exec sudo "$0" "$@"
		return $?
	fi

	export DEBIAN_FRONTEND=noninteractive

	apt update

	# sync with install.sh, m/i/Dockerfile
	apt install -y \
		make direnv curl xz-utils dirmngr gpg pcscd scdaemon gpg-agent rsync \
		build-essential sudo ca-certificates tzdata locales git git-lfs tini \
		iproute2 iptables bc pv socat docker.io s6 cpu-checker bind9-dnsutils \
		pass

	apt update && apt install -y \
		wireguard-tools qemu-system libvirt-clients libvirt-daemon-system \
		openvpn easy-rsa expect tpm2-tools zfsutils-linux ubuntu-drivers-common

	ln -sf /usr/share/zoneinfo/UTC /etc/localtime
	dpkg-reconfigure -f noninteractive tzdata

	tee /etc/apt/apt.conf.d/local <<EOF
DPkg::Lock::Timeout "-1";
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};
EOF

	tee /etc/apt/apt.conf.d/99-Phased-Updates <<EOF
Update-Manager::Never-Include-Phased-Updates;
APT::Get::Never-Include-Phased-Updates: True;
EOF

	groupadd -g 1000 ubuntu && useradd -u 1000 -d /home/ubuntu -s /bin/bash -g ubuntu -M ubuntu

	# need docker accessible because install.sh won't be run in the AMI
	usermod -aG docker ubuntu

	echo 'ubuntu ALL=(ALL:ALL) NOPASSWD: ALL' >/etc/sudoers.d/ubuntu

	install -d -m 0700 -o ubuntu -g ubuntu /home/ubuntu
	chown -R ubuntu:ubuntu /home/ubuntu && chmod u+s /usr/bin/sudo

	curl -v -fsSL https://tailscale.com/install.sh | bash -x
	rm -rf /var/lib/tailscale

	(
		echo net.ipv4.ip_forward=1
		echo net.ipv6.conf.all.forwarding=1
		echo fs.inotify.max_user_instances=10000
		echo fs.inotify.max_user_watches=524288
	) | tee /etc/sysctl.d/99-dfd.conf

	mkdir -p /etc/systemd/network
	pushd /etc/systemd/network

	local a
	a=1

	(
		echo "[NetDev]"
		echo Name=dummy"$a"
		echo Kind=dummy
	) | sudo tee dummy"$a".netdev

	(
		echo "[Match]"
		echo Name=dummy"$a"
		echo
		echo "[Network]"
		echo Address=169.254.32."$a"/32
	) | sudo tee dummy"$a".network

	popd
}

main "$@"
