#!/usr/bin/env bash

function main {
	set -exfu
	STARSHIP_PREEXEC_READY=

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		cd

		# root stuff
		sudo "$0" "$@"

		# clone defn/dev to $HOME
		git clone https://github.com/defn/dev
		mv dev/.git .
		rm -rf dev
		git reset --hard

		sudo apt install -y pipx
		make play

		exit $?
	fi

	export DEBIAN_FRONTEND=noninteractive

	apt update || true
	apt update
	apt install -y git make curl

	curl -fsSL https://tailscale.com/install.sh | bash -x
	rm -rf /var/lib/tailscale

	if [[ ! -x "/usr/local/bin/bazel" ]]; then
		case "$(uname -m)" in
		aarch64) sudo curl -sSL -o /usr/local/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-arm64 ;;
		*) sudo curl -sSL -o /usr/local/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 ;;
		esac
	fi

	sudo chmod 755 /usr/local/bin/bazelisk
	sudo ln -nfs bazelisk /usr/local/bin/bazel

	sudo install -d -m 0755 /etc/docker
	echo '{ "insecure-registries" : ["169.254.32.1:4999", "cache.defn.run:4999", "coder-amanibhavam-district.tail3884f.ts.net:5000", "district.tail3884f.ts.net:5000"] }' | sudo tee /etc/docker/daemon.json

	(
		echo net.ipv4.ip_forward=1
		echo net.ipv6.conf.all.forwarding=1
		echo fs.inotify.max_user_instances=10000
		echo fs.inotify.max_user_watches=524288
	) | sudo tee /etc/sysctl.d/99-dfd.conf

	sudo mkdir -p /etc/systemd/network
	pushd /etc/systemd/network

	local a
	a=1

	(
		echo "[NetDev]"
		echo Name=dummy"$a"
		echo Kind=dummy
	) | sudo tee dummy"$a".netdev

	(
		echo "[Match]"
		echo Name=dummy"$a"
		echo
		echo "[Network]"
		echo Address=169.254.32."$a"/32
	) | sudo tee dummy"$a".network

	popd
}

main "$@"
