#!/usr/bin/env bash

function main {
	set -exfu

	export STARSHIP_PREEXEC_READY=
	export DEBIAN_FRONTEND=noninteractive

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		cd

		git clone https://github.com/defn/dev
		mv dev/.git .
		rm -rf dev
		git reset --hard

		set +x
		source .bash_profile
		set -x
		make nix sync install

		cd m
		b clean
	fi
}

main "$@"
