#!/usr/bin/env bash

function main {
	set -exfu
	STARSHIP_PREEXEC_READY=

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		cd
		git fetch origin
		git reset --hard origin/main

		sudo apt update
		sudo apt install -y make
		make vpn-install

		local ssd="/dev/$( (
			df -klh / | grep /dev/ | awk '{print $1}' | sed 's#p1$##' | cut -d/ -f3
			lsblk | grep ^nvme | awk '{print $1}'
		) | sort | uniq -c | grep ' 1 ' | awk '{print $2}')"

		sudo zpool create nix "$ssd"
		sudo zfs set mountpoint=/nix nix
		sudo zfs set atime=off nix
		sudo zfs set compression=on nix
		sudo chown ubuntu:ubuntu /nix

		sudo zfs create nix/work
		sudo zfs set mountpoint=/home/ubuntu/work nix/work
		sudo zfs set atime=off nix/work
		sudo zfs set compression=off nix/work
		sudo chown ubuntu:ubuntu /home/ubuntu/work

		set +xu
		source .bash_profile
		set -xu

		git config --global user.email "you@example.com"
		git config --global user.name "Your Name"
		touch m/.bazelrc.user
		make install

		sudo zfs snapshot nix@install
		sudo zfs snapshot nix/work@install
		sudo zfs send nix@install | pv >/nix.zfs
		sudo zfs send nix/work@install | pv >/work.zfs

		exit $?
	fi
}

main "$@"
