#!/usr/bin/env bash

function main {
	set -exfu

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		cd
		git pull

		set +x
		source .bash_profile
		set -x

		git config --global user.email "you@example.com"
		git config --global user.name "Your Name"
		make install
		git checkout .
		
		make play
		make upgrade

		exit $?
	fi
}

main "$@"
