#!/usr/bin/env bash

function main {
	set -exfu
	STARSHIP_PREEXEC_READY=

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		cd
		git pull

		set +exfu
		source .bash_profile
		set -exfu

		make install

		cd m/pb
		make demo opt="-e ansible_connection=local -l localhost"

		exit $?
	fi
}

main "$@"
