#!/usr/bin/env bash

exec 2>&1

export STARSHIP_NO=1
source ~/.bash_profile
mise trust
mise install
source .env
export PATH

exec mise exec -- coder server --enable-terraform-debug-mode \
	--derp-force-websockets \
	--oauth2-github-device-flow=false \
	--oauth2-github-allow-signups="${CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS}" \
	--oauth2-github-allowed-orgs="${CODER_OAUTH2_GITHUB_ALLOWED_ORGS}" \
	--oauth2-github-allowed-teams="${CODER_OAUTH2_GITHUB_ALLOWED_TEAMS}" \
	--http-address "${CODER_HTTP_ADDRESS:-127.0.0.1:3000}" \
	--access-url https://"${CODER_ACCESS_URL:-${CODER_SERVER_NAME:+coder.${CODER_SERVER_NAME}.}${CODER_SERVER_DOMAIN}}" \
	${CODER_EXTRA_ARGS:---wildcard-access-url "*.${CODER_SERVER_NAME:+${CODER_SERVER_NAME}.}${CODER_SERVER_DOMAIN}"}
