#!/usr/bin/env bash

exec 2>&1

export STARSHIP_NO=1
source ~/.bash_profile
direnv allow
mise trust
source .env

export PATH

exec mise exec -- coder server --enable-terraform-debug-mode \
	--oauth2-github-device-flow="${CODER_OAUTH2_GITHUB_DEVICE_FLOW}" \
	--oauth2-github-allow-signups="${CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS}" \
	--oauth2-github-allowed-orgs="${CODER_OAUTH2_GITHUB_ALLOWED_ORGS}" \
	--oauth2-github-allowed-teams="${CODER_OAUTH2_GITHUB_ALLOWED_TEAMS}" \
	--access-url "https://coder.${CODER_SERVER_NAME}.${CODER_SERVER_DOMAIN}" \
	--wildcard-access-url "*.${CODER_SERVER_NAME}.${CODER_SERVER_DOMAIN}"

#	--oauth2-github-client-id ${coder_oauth2_github_client_id} \
#	--oauth2-github-client-secret ${coder_oauth2_github_client_secret} \
#	--access-url "https://coder.${CODER_SERVER_NAME}.$${CODER_SERVER_DOMAIN}" \
#	--wildcard-access-url "*.${CODER_SERVER_NAME}.$${CODER_SERVER_DOMAIN}" \
#	--tls-cert-file ${CODER_SERVER_NAME}.$${CODER_SERVER_DOMAIN}/fullchain.pem \
#	--tls-key-file ${CODER_SERVER_NAME}.$${CODER_SERVER_DOMAIN}/privkey.pem \
#	--tls-enable --derp-force-websockets
