build:
	rm -rf build/web
	mkdir -p build/web
	./bin/godot --headless -v --export-release Web ./build/web/index.html
	curl -fsSL https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.js > build/web/coi-serviceworker.js
	sed -i 's#\(             <script src="index.js"></script>\)#             <script src="coi-serviceworker.js"></script>\n\1#g' build/web/index.html

serve:
	cd gen && python -m http.server

install:
	$(MAKE) install-godot install-templates

install-godot:
	mkdir -p bin
	curl -sSL -O https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
	unzip -o Godot_v4.2.1-stable_linux.x86_64.zip
	rm -f Godot_v4.2.1-stable_linux.x86_64.zip
	mkdir -p bin
	mv -f Godot_v4.2.1-stable_linux.x86_64 bin/godot

install-templates:
	curl -sSL -O https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
	unzip -o Godot_v4.2.1-stable_export_templates.tpz
	rm -f Godot_v4.2.1-stable_export_templates.tpz
	mkdir -p ~/.local/share/godot/export_templates/4.2.1.stable
	mv templates/* ~/.local/share/godot/export_templates/4.2.1.stable/

all:
	$(MAKE) build serve