#!/usr/bin/env python

load("../common/Tiltfile", "main")

local_resource(
    "sound",
    serve_cmd=[
        "bash",
        "-c",
        """
            exec make sound
        """,
    ],
)

local_resource(
    "pixel",
    serve_cmd=[
        "bash",
        "-c",
        """
            exec make pixel
        """,
    ],
)

local_resource(
    "level",
    serve_cmd=[
        "bash",
        "-c",
        """
            exec make level
        """,
    ],
)
