// Code generated by wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli

import (
	"context"
	"encoding/json"
	"io"

	cliclient "github.com/defn/dev/m/tilt/internal/cli/client"
	"github.com/defn/dev/m/tilt/internal/engine"
	"github.com/defn/dev/m/tilt/internal/hud"
	"github.com/defn/dev/m/tilt/internal/hud/prompt"
	"github.com/defn/dev/m/tilt/pkg/model"
)

func wireTiltfileResult(ctx context.Context, subcommand model.TiltSubcommand) (cmdTiltfileResultDeps, error) {
	// TODO: Implement wire generation
	return cmdTiltfileResultDeps{}, nil
}

func wireCmdUp(ctx context.Context, subcommand model.TiltSubcommand) (CmdUpDeps, error) {
	// TODO: Implement wire generation
	return CmdUpDeps{}, nil
}

func wireCmdCI(ctx context.Context, subcommand model.TiltSubcommand) (CmdCIDeps, error) {
	// TODO: Implement wire generation
	return CmdCIDeps{}, nil
}

func wireLogsDeps(ctx context.Context, subcommand model.TiltSubcommand) (LogsDeps, error) {
	// TODO: Implement wire generation
	return LogsDeps{}, nil
}

func wireClientGetter(ctx context.Context) (*cliclient.Getter, error) {
	// TODO: Implement wire generation
	return nil, nil
}

// encodeJSON encodes v to JSON and writes to w
func encodeJSON(w io.Writer, v interface{}) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

// Types from wire.go that need to be accessible
type CmdUpDeps struct {
	Upper     engine.Upper
	TiltBuild model.TiltBuild
	Prompt    *prompt.TerminalPrompt
}

type CmdCIDeps struct {
	Upper     engine.Upper
	TiltBuild model.TiltBuild
}

type LogsDeps struct {
	printer *hud.IncrementalPrinter
	filter  hud.LogFilter
}
