// Code generated by wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli

import (
	"context"
	"encoding/json"
	"io"

	cliclient "github.com/defn/dev/m/tilt/internal/cli/client"
	"github.com/defn/dev/m/tilt/internal/analytics"
	"github.com/defn/dev/m/tilt/internal/engine"
	"github.com/defn/dev/m/tilt/internal/hud"
	"github.com/defn/dev/m/tilt/internal/hud/prompt"
	"github.com/defn/dev/m/tilt/internal/token"
	"github.com/defn/dev/m/tilt/pkg/logger"
	"github.com/defn/dev/m/tilt/pkg/model"
)

func wireTiltfileResult(ctx context.Context, a *analytics.TiltAnalytics, subcommand model.TiltSubcommand) (cmdTiltfileResultDeps, error) {
	// TODO: Implement wire generation
	return cmdTiltfileResultDeps{}, nil
}

func wireCmdUp(ctx context.Context, a *analytics.TiltAnalytics, subcommand model.TiltSubcommand) (CmdUpDeps, error) {
	// TODO: Implement wire generation
	return CmdUpDeps{}, nil
}

func wireCmdCI(ctx context.Context, a *analytics.TiltAnalytics, subcommand model.TiltSubcommand) (CmdCIDeps, error) {
	// TODO: Implement wire generation
	return CmdCIDeps{}, nil
}

func wireLogsDeps(ctx context.Context, tiltAnalytics *analytics.TiltAnalytics, subcommand model.TiltSubcommand) (LogsDeps, error) {
	// TODO: Implement wire generation
	return LogsDeps{}, nil
}

func wireAnalytics(l logger.Logger, cmdName model.TiltSubcommand) (*analytics.TiltAnalytics, error) {
	// Return a disabled analytics for now
	return nil, nil
}

func wireClientGetter(ctx context.Context) (*cliclient.Getter, error) {
	// TODO: Implement wire generation
	return nil, nil
}

func wireLsp(ctx context.Context, l logger.Logger, subcommand model.TiltSubcommand) (cmdLspDeps, error) {
	// TODO: Implement wire generation
	return cmdLspDeps{}, nil
}

// encodeJSON encodes v to JSON and writes to w
func encodeJSON(w io.Writer, v interface{}) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

// Types from wire.go that need to be accessible
type CmdUpDeps struct {
	Upper     engine.Upper
	TiltBuild model.TiltBuild
	Token     token.Token
	Prompt    *prompt.TerminalPrompt
}

type CmdCIDeps struct {
	Upper        engine.Upper
	TiltBuild    model.TiltBuild
	Token        token.Token
	Snapshotter  *stubSnapshotter
	CloudAddress string
}

type LogsDeps struct {
	printer *hud.IncrementalPrinter
	filter  hud.LogFilter
}

type stubSnapshotter struct{}

func (s *stubSnapshotter) WriteSnapshot(ctx context.Context, path string) error {
	return nil
}
