#!/usr/bin/env bash

#MISE description="Build Astro static site artifacts"

set -efu -o pipefail

cd "${MISE_ORIGINAL_CWD}"
pnpm run astro build "$@"

for d in MyDurableObject; do
	echo
	echo "export { M as ${d} } from './$(egrep -r ^class.${d} dist | cut -d: -f1 | cut -d/ -f3-)';"
	echo
done >>dist/_worker.js/index.js
