#!/usr/bin/env bash

#MISE description="Deploy Astro artifacts to Cloudflare workers"

set -efu -o pipefail

cd "${MISE_ORIGINAL_CWD}"
pnpm wrangler deploy -c wrangler-do.toml
pnpm wrangler deploy -c wrangler.toml
