# Push workspace template to Coder
# Description: Packages and pushes a Coder template to the server, then sets default TTL
# Dependencies: coder CLI, tar command, valid template directory
# Outputs: Updates template in Coder server with 1 hour default TTL
[no-cd]
push template:
	#!/usr/bin/env bash

	cd {{template}}
	tar -cvh --exclude .terraform . | coder templates push -y -d - {{template}}
	coder templates edit --default-ttl 1h {{template}}
