#!/usr/bin/env python

# fuck off
analytics_settings(False)

load("ext://restart_process", "custom_build_with_restart")

# local k8s
allow_k8s_contexts('dfd-amanibhavam-dev')

# local registry
default_registry("169.254.32.1:5000")

# hook build
local_resource(name="hook-build", cmd="true", deps=["./hooks"])

# hook initial deploy
k8s_yaml(local("cat main.yaml"))

# hook service selected from deploy
k8s_resource("hook", resource_deps=["hook-build"])

# hook updates when hook updates
custom_build_with_restart(
    ref="hook",
    command="make build image=$EXPECTED_REF",
    entrypoint=["/shell-operator"],
    deps=["./hooks"],
    trigger=["./hooks"],
    live_update=[
        sync("./hooks", "/hooks"),
    ],
)
