#!/usr/bin/env python

load("ext://restart_process", "custom_build_with_restart")

# local k8s
allow_k8s_contexts("coder-amanibhavam-district0-cluster")

# local registry
default_registry("coder-amanibhavam-district.tail3884f.ts.net:5000")

local_resource(
    name="tutorial",
    cmd="cue eval --out json -e html | jq -r . > tutorial.html",
    deps=["tutorial.cue"],
)

local_resource(
    name="config",
    cmd="for h in hook; do cue export -p l --out json -e hooks.$h.config > hooks/$h.json; done",
    deps=["hook.cue"],
)

# hook initial deploy
k8s_yaml(local('bash -c "cat deploy.yaml"'))

# hook build
local_resource(name="hook-build", cmd="true", deps=["./hooks"])

# hook service
k8s_resource("hook", resource_deps=["hook-build"])

# hook live update
custom_build_with_restart(
    ref="hook",
    command="make build image=$EXPECTED_REF",
    entrypoint=["/shell-operator"],
    deps=["./hooks"],
    trigger=["./hooks"],
    live_update=[
        sync("./hooks", "/hooks"),
    ],
)
