#!/usr/bin/env bash

function main {
	set -exfu

	if [[ "$(whoami)" == "ubuntu" ]]; then
		exec sudo "$0" "$@"
		return $?
	fi

	cat <<EOF | tee /etc/apt/apt.conf.d/local
DPkg::Lock::Timeout "-1";
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};
EOF

	apt update
	apt purge --auto-remove -y unattended-upgrades
}

main "$@"
