#!/usr/bin/env bash

function main {
	set -exfu

	if [[ "$(whoami)" == "ubuntu" ]]; then
		exec sudo "$0" "$@"
		return $?
	fi

	export LANG=en_US.UTF-8
	export LANGUAGE=en_US:en
	export LC_ALL=en_US.UTF-8
	export DEBIAN_FRONTEND=noninteractive

	apt-get update && apt-get upgrade -y &&
		apt-get install -y --no-install-recommends lsb-release tzdata locales ca-certificates wget curl xz-utils rsync make git direnv bash-completion less pass \
			sudo tini procps iptables net-tools iputils-ping iproute2 dnsutils gnupg \
			openssh-client fzf build-essential \
			linux-generic-hwe-22.04 &&
		apt-get clean && apt purge -y nano &&
		rm -f /usr/bin/gs

	apt update && apt upgrade -y

	ln -sf /usr/share/zoneinfo/UTC /etc/localtime &&
		dpkg-reconfigure -f noninteractive tzdata &&
		locale-gen en_US.UTF-8 &&
		localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

	groupadd -g 1000 ubuntu && useradd -u 1000 -d /home/ubuntu -s /bin/bash -g ubuntu -M ubuntu &&
		echo '%ubuntu ALL=(ALL:ALL) NOPASSWD: ALL' >/etc/sudoers.d/ubuntu &&
		install -d -m 0700 -o ubuntu -g ubuntu /home/ubuntu

	mkdir -p /etc/systemd/network
	pushd /etc/systemd/network
	for a in 1; do
		(
			echo [NetDev]
			echo Name=dummy"${a}"
			echo Kind=dummy
		) | tee dummy"${a}".netdev

		(
			echo [Match]
			echo Name=dummy"${a}"
			echo
			echo [Network]
			echo Address=169.254.32."${a}"/32
		) | tee dummy"${a}".network
	done
}

main "$@"
