#!/usr/bin/env bash

function main {
	set -exfu

	if [[ "$(whoami)" == "ubuntu" ]]; then
		exec sudo "$0" "$@"
		return $?
	fi

	export DEBIAN_FRONTEND=noninteractive

	wget https://downloads.nestybox.com/sysbox/releases/v0.5.0/sysbox-ce_0.5.0-0.linux_amd64.deb
	dpkg -i sysbox-ce_0.5.0-0.linux_amd64.deb
	rm -f sysbox-ce_0.5.0-0.linux_amd64.deb

	cat /etc/docker/daemon.json | jq '."default-runtime" = "sysbox-runc"' >1
	mv 1 /etc/docker/daemon.json
}

main "$@"
