#!/usr/bin/env bash

function main {
	set -exfu

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		exec sudo "$0" "$@"
		return $?
	fi

	curl -sSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64 &&
		chmod 755 /usr/local/bin/bazel

	install -d -m 0755 -o root -g root /run/user &&
		install -d -m 0700 -o root -g root /run/sshd &&
		install -d -m 0700 -o ubuntu -g ubuntu /run/user/1000 /run/user/1000/gnupg /nix
}

main "$@"
