#!/usr/bin/env bash

function main {
	set -exfu

	if ! [[ "$(whoami)" == "ubuntu" ]]; then
		exec sudo -H -i -u ubuntu "$0" "$@"
		return $?
	fi

	ssh -o StrictHostKeyChecking=no git@github.com true || true
	git clone https://github.com/defn/dev home
	mv home/.git .
	git reset --hard
	git submodule update --init
	git clean -fdx
}

main "$@"
