#!/usr/bin/env bash

function main {
	set -exfu

	if [[ "$(whoami || true)" == "ubuntu" ]]; then
		sudo "$0" "$@"

		cd
		git clone https://github.com/defn/dev
		mv dev/.git .
		rm -rf dev
		git reset --hard
		source .bash_profile

		make install

		exit $?
	fi

	export DEBIAN_FRONTEND=noninteractive

	apt-get update
	apt-get install -y build-essential fzf jq gettext direnv net-tools curl

	apt-get install -y docker.io
	usermod -aG docker ubuntu

	curl -fsSL https://tailscale.com/install.sh | sh
	rm -rf /var/lib/tailscale

	if [[ ! -x "/usr/local/bin/bazel" ]]; then
		case "$(uname -m)" in
			aarch64) sudo curl -sSL -o /usr/local/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-arm64 ;;
			*) sudo curl -sSL -o /usr/local/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 ;;
		esac
	fi

	sudo chmod 755 /usr/local/bin/bazelisk
	sudo ln -nfs bazelisk /usr/local/bin/bazel

	echo '{ "insecure-registries" : ["169.254.32.1:5000", "cache.defn.run:5000"] }' | sudo tee /etc/docker/daemon.json

	(
		echo net.ipv4.ip_forward=1
		echo net.ipv6.conf.all.forwarding=1
		echo fs.inotify.max_user_instances=10000
		echo fs.inotify.max_user_watches=524288 
	) | sudo tee /etc/sysctl.d/99-dfd.conf

	sudo mkdir -p /etc/systemd/network
	pushd /etc/systemd/network

	local a
	a=1

	(
		echo "[NetDev]"
		echo Name=dummy"$a"
		echo Kind=dummy
	) | sudo tee dummy"$a".netdev

	(
		echo "[Match]"
		echo Name=dummy"$a"
		echo
		echo "[Network]"
		echo Address=169.254.32."$a"/32
	) | sudo tee dummy"$a".network

	popd
}

main "$@"
