VERSION 0.7

build:
    ARG image=169.254.32.1:5000/dfd
    BUILD +build-pod --image=${image}

build-pod:
    ARG image
    BUILD +image-pod --image=${image}

image-pod:
    ARG image

    FROM +pod
    SAVE IMAGE --push ${image}

pod:
    FROM quay.io/defn/dev:latest

    RUN git clone https://github.com/defn/dev dev \
        && mv dev/.git . \
        && rm -rf dev \
        && git reset --hard

    RUN bash -c 'source .bashrc && make nix home'

    RUN bash -c 'source .bashrc && code --install-extension vscodevim.vim'
