#!/usr/bin/env bash

#MISE description="Create an issue and work on it"
#USAGE arg "title" help="The issue title"

cd "${MISE_ORIGINAL_CWD}"

while ! gh auth token >/dev/null; do
	gh auth login
done

# create the issue with the title, assign to yourself
gh issue create --assignee '@me' --title "${usage_title}" --body ''

# search for the same issue by title to get the issue number
issue=
while test -z "${issue}"; do
	sleep 1
	issue="$(gh issue ls --search "${usage_title}" --json number | jq -r '.[0].number // ""')"
done

# let m work check out the issue branch
mise run work "$issue"
