#!/usr/bin/env bash

#MISE description="Run a remote command with Ansible"
#USAGE arg "limit" help="Limit to hosts" default="none"
#USAGE arg "cmd" help="Remote command" default="true"
#USAGE arg "format" help="Output format" default="default"

cd "${MISE_ORIGINAL_CWD}"

export ANSIBLE_LOAD_CALLBACK_PLUGINS=1
export ANSIBLE_STDOUT_CALLBACK="${usage_format}"

ansible "${usage_limit}" -m shell -a "${usage_cmd}"
