#!/usr/bin/env bash

#MISE description="Start an s6 service"
#USAGE arg "path" help="Path to a service directory" default=""

set -efu -o pipefail

cd "${MISE_ORIGINAL_CWD}"

if [[ -n "${usage_path}" ]]; then
	cd "${usage_path}"
fi

case "$(basename "$(pwd)")" in
	svc)
		echo "ERROR: s6-svscandir restart not implemented" 1>&2
		exit 1
		;;
	*)
		mise run stop
		mise run start
		;;
esac
