#!/usr/bin/env bash

#MISE description="Run a s6 supervisor"

cd "${MISE_ORIGINAL_CWD}"
mkdir -p svc
ln -nfs ../svc.d/main svc/
setsid env - HOME=$HOME USER=$USER HOSTNAME=$HOSTNAME s6-svscan $(pwd)/svc &>/dev/null &
while ! s6-svscanctl -a svc; do date; sleep 1; done
