#!/usr/bin/env bash

#MISE description="Start an s6 service"
#USAGE arg "path" help="Path to a service directory" default=""

set -efu -o pipefail

cd "${MISE_ORIGINAL_CWD}"

if [[ -n "${usage_path}" ]]; then
	cd "${usage_path}"
fi

case "$(basename "$(pwd)")" in
	svc)
		cd ..
		mise run serve		
		;;
	*)
		if ! s6-svstat . >/dev/null; then
			(cd ../../svc && mise run activate)
			while ! s6-svstat . >/dev/null 2>&1; do
				sleep 1
			done
		fi
		s6-svc -u .
		while ! s6-svstat . | grep ^up; do
			sleep 1
		done
		;;
esac
