#!/usr/bin/env bash

#MISE description="Get the status of an s6 service"
#USAGE arg "path" help="Path to a service directory" default=""

set -efu -o pipefail

cd "${MISE_ORIGINAL_CWD}"

if [[ -n ${usage_path} ]]; then
	if test -d "svc/${usage_path}/."; then
		cd "svc/${usage_path}"
	elif test -d "${usage_path}"; then
		cd "${usage_path}/."
	fi
fi

if test -d svc; then
	cd svc
fi

case "$(basename "$(pwd)")" in
svc)
	set +f
	runmany 'if test -d $1; then cd $1 && echo "$(basename $(pwd)) $(mise run status 2>/dev/null)"; fi' */ | sort | talign 2
	set -f
	;;
*)
	s6-svstat .
	;;
esac
