#!/usr/bin/env bash

#MISE description="Create a branch for issue or PR"
#USAGE arg "thing" help="The issue or PR to work on"

cd "${MISE_ORIGINAL_CWD}"

while ! gh auth token >/dev/null; do
	gh auth login
done

branch="$(gh issue view "${usage_thing}" --json number,title | jq -r '"\(.number)-\(.title)" | gsub("[^a-zA-Z0-9]+"; "-") | ascii_downcase')"
if [[ -z ${branch} ]]; then
	echo "ERROR: can't find issue or branch ${thing}" 2>&1
	exit 1
fi

# always proceed from main branch
(
	cd
	git checkout main
	make sync
)

# try creating the branch
if git checkout -b "${branch}"; then
	git push -u origin "$(git rev-parse --abbrev-ref HEAD)"

# otherwise, check out the branch
else
	git checkout "${branch}"
fi

# sync again to pick up branch settings
git merge origin/main
git pull

cd
make sync
