#!/usr/bin/env python

local_resource(
    "build",
    cmd=[
        "bash",
        "-c",
        """
            exec make build
        """,
    ],
)

local_resource(
    "dev",
    serve_cmd=[
        "bash",
        "-c",
        """
            exec make dev
        """,
    ],
)
