#!/usr/bin/env python

v1alpha1.extension_repo(name="custom", load_host="defn", url="file:///home/ubuntu/m")

load("ext://defn/common", "main")

local_resource(
    "build",
    serve_cmd=[
        "bash",
        "-c",
        """
            exec make build
        """,
    ],
)

local_resource(
    "server",
    serve_cmd=[
        "bash",
        "-c",
        """
            exec make server
        """,
    ],
    deps=[
        "../bazel-bin/wg/wg_/wg"
    ]
)

local_resource(
    "client",
    serve_cmd=[
        "bash",
        "-c",
        """
            while true; do
                make client
                sleep 60
            done
        """,
    ],
    deps=[
        "../bazel-bin/wg/wg_/wg"
    ]
)
