#!/usr/bin/env bash

vc="$1"; shift

if curl -sSL -m 1 dev-x-default-x-vcluster.${vc}/d | grep -q Unauthorized; then
    exec socat - TCP:dev-x-default-x-vcluster.${vc}:80
else
    echo HTTP/1.1 200
    echo
    cat index.html

    # provision infra for user
    if flock -n .doing.${vc} -c "./provision-vcluster ${vc}"; then
        true
    fi
fi
