#!/usr/bin/env bash

vc="$1"; shift

if curl -sSL -M 1 dev-x-default-x-vcluster.${vc} | grep -s /login; then
    exec socat - TCP:dev-x-default-x-vcluster.${vc}:80
else
    echo HTTP/1.1 200
    echo
    cat index.html

    # provision infra for user
    if flock -n .doing.${vc} -c "./vcluster ${vc}"; then
        true
    fi
fi
