#!/usr/bin/env bash

vc="$1"; shift

if [[ -f .done.${vc} ]]; then
    exec socat - TCP:dev-x-default-x-vcluster.${vc}:80
else
    echo HTTP/1.1 200
    echo
    cat index.html

    # provision infra for user
    if flock -n .doing.${vc} -c "true"; then
        exec 1>&2
        app sync ${vc}
        app wait ${vc}
        app sync ${vc}-dev
        app wait ${vc}-dev
        touch .done.${vc}
        rm -f .doing.${vc}
    fi
fi
