#!/usr/bin/env bash

exec 2>&1

export STARSHIP_NO=
source ~/.bash_profile

if [[ -f .env ]]; then
	source .env
fi

if [[ -n ${CODER_AGENT_URL_ORIGINAL-} ]]; then
	export VSCODE_PROXY_URI="https://{{{{port}}--main--${CODER_NAME}--${GIT_AUTHOR_NAME}.${CODER_AGENT_URL_ORIGINAL#https://coder.}/"
fi

exec code-server --auth none
