VERSION --use-registry-for-with-docker --ci-arg 0.7

build:
    ARG image=quay.io/defn/dev:latest-bazel
    BUILD --platform=linux/amd64 +image --image=${image}
    BUILD --platform=linux/arm64 +image --image=${image}

image:
    FROM ubuntu
    ARG image
    COPY aws_config.txt .
    COPY app_config .
    SAVE IMAGE --push ${image}