up:
    tilt up

server:
    python -m venv venv
    venv/bin/pip install -r requirements.txt
    venv/bin/python main.py

build:
    b build
    b run tutorial_html__copy
    chmod 0640 tutorial.html
    trunk fmt tutorial.html

check:
    echo File-systems using LVM:
    echo
    df -klh | head -1
    df -klh | grep /dev/mapper
    echo
    echo Free volume group disk:
    echo
    sudo vgdisplay | grep Free