#!/usr/bin/env bash

function main {
    mkdir -p /var/lib/tailscale
    echo "${DEFN_DEV_TAILSCALE_STATE}" | base64 -d > /var/lib/tailscale/tailscaled.state
    (setsid /usr/sbin/tailscaled --statedir=/var/lib/tailscale) &

    (setsid sudo -u ubuntu -H --preserve-env=PASSWORD ~ubuntu/bin/e code-server --bind-addr 0.0.0.0:8888 --disable-telemetry) &

    cat > Caddyfile <<EOF
https://${DEFN_DEV_HOST} {
	reverse_proxy http://localhost:8888
}
EOF
    (setsid "$(~ubuntu/bin/e asdf which caddy)" run) &

    sleep 5
    tailscale up --ssh --hostname "$(echo "${DEFN_DEV_HOST}" | cut -d. -f1)"

    exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o StreamLocalBindUnlink=yes
}

main "$@"
