#!/usr/bin/env bash

function main {
    mkdir -p /var/lib/tailscale
    echo "${DEFN_DEV_TAILSCALE_STATE}" | base64 -d > /var/lib/tailscale/tailscaled.state
    (setsid /usr/sbin/tailscaled --statedir=/var/lib/tailscale) &
    exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o StreamLocalBindUnlink=yes
}

main "$@"
